### ISSUE TITLE
content/en/_index.md not mentioned in tutorial

### ISSUE THREAD

**Issue by StefanSalewski** [h-enk/doks#1036]
Dear Sir,

I started yesterday with Hugo and its tutorial. Today, I tried your doks theme, again following the tutorial. In

https://getdoks.org/docs/tutorial/set-configuration/

we have

```
Open ./config/_default/params.toml

Change these settings:

## Homepage
title = "Doks"
titleSeparator = "-"
titleAddition = "Modern Documentation Theme"
description = "Doks is a Hugo theme for building secure, fast, and SEO-ready documentation websites, which you can easily update and customize."
```

I had the feeling, that changing titleAddition or description had no effects.

After finding the string literals with grep, I finally modified content/en/_index.md and the running local webserver immediately updated the main page in firefox.

Did I something wrong, or may the tutorial be outdated? Maybe I did something wrong, I will repeat all actions later this day from scratch, and tell you if I made indeed a mistake.

**Comment by StefanSalewski** [comment]
Well, from comment

```
Set meta data for Search Engine Optimization (SEO) and Social Media.
```

I may get the feeling, that it is no real issue. The content may be just metadata and never got displayed. But for that case, it would make it for beginner easier, when the meta content is not identical to the shown text.

Next Problem:

JSON-LD

Change these settings:

...
schemaAuthor = "Henk Verlinde"

Well, should I really change the entries? I think the schemaAuthor is Henk Verlinde and not me?

**Comment by h-enk** [comment]
Thanks for using Doks!

> Did I something wrong, or may the tutorial be outdated?

No, you did not! You found a bug w/ Chromium browsers (will be fixed in the soon to be released Doks 1.0).  You'll just need to add `--noHTTPCache` to the `start` script in `package.json`, like so:

```json
    "start": "exec-bin node_modules/.bin/hugo/hugo server --gc --bind=0.0.0.0 --disableFastRender --baseURL=http://localhost --noHTTPCache",
```

**Comment by StefanSalewski** [comment]
Thank you very much for your fast reply.

**Comment by h-enk** [comment]
> [..] it would make it for beginner easier, when the meta content is not identical to the shown text.

Get that, will be looking in auto fill possibilities when using the [CLI](https://github.com/gethyas/create-hyas) for setting up a new Doks project.

> Well, should I really change the entries? I think the schemaAuthor is Henk Verlinde and not me?

No, the meta data should be completely yours. It's based on the Schema.org approach by Yoast SEO — for more background, see [Schema - Background information](https://developer.yoast.com/features/schema/background/)
