### ISSUE TITLE
No CSS for deploy

### ISSUE THREAD

**Issue by StefanSalewski** [h-enk/doks#1041]
>I assume and hope that deploying will work as well.

Sorry, one more tiny issue.

I just tried to deploy, to all-inkl.com.

A week ago I followed the Hugo tutorial, and deploy worked fine.

Now I tried for your doks theme. Not following you instructions at https://getdoks.org/docs/tutorial/deploy-your-site/ as I have no Netlify.

So it is basically just "hugo" and then ssh upload as explained in https://gohugo.io/hosting-and-deployment/deployment-with-rsync/.

Upload works, but there seems to be no CSS. See

https://nimprogramming.com/

My guess is supported by

```
$ du -h -d1 public/
0	public/css
1.6M	public/fonts
620K	public/blog
0	public/images
124K	public/js
1.7M	public/videos
68K	public/faq
60K	public/code-snippets
52K	public/about
56K	public/tutorials
24K	public/categories
56K	public/books
24K	public/contributors
24K	public/tags
4.6M	public/
```

But I have no idea why hugo generates no CSS in public folder. Have done some Google search already, but no luck.

**Comment by StefanSalewski** [comment]
Fixed :-)

https://getdoks.org/docs/tutorial/deploy-your-site/

Make sure to set baseURL in ./config/production/config.toml to the URL of your Doks website in production.

$ cat ./config/production/config.toml
canonifyURLs = false
baseURL = 'https://nimprogramming.com/'

**Comment by h-enk** [comment]
Closing this one then

**Comment by xunx911** [comment]
Thank you very much,the same problem,and the config.toml is named hugo.toml now
