### ISSUE TITLE
BaseUrl not applied on static images when using canonifyURLs

### ISSUE THREAD

**Issue by simonstumpf** [h-enk/doks#1048]
## Description

All of my images are in the `static` directory. When running the server local, all images can be displayed. 
However when I deploy it with Gitlab Pages, everything works as expected, except static images. 

The website tries to load the images from `https://site.pages.my-gitlab.com/image.png` instead of `https://site.pages.my-gitlab.com/my-space/image.png`. When entering the second URL directly, the image is shown. 

Here is my config.toml in the production directory:
```
canonifyURLs = true
baseurl = "https://site.pages.my-gitlab.com/my-space/"
```
### Steps to reproduce

- Use the child theme
- Add images to the static directory
- Refer to the image like this `![Permissions Group Overview](gitlab-modify-permissions.png)`
- Deploy doks to Gitlab

### Expected result

The url of static images should apply the baseURL.

### Actual result

The configured baseURL is ignored. 

### Environment
```

> doks-child-theme@0.5.0 precheck
> npm version

{
  'doks-child-theme': '0.5.0',
  npm: '9.5.1',
  node: '19.8.1',
  acorn: '8.8.2',
  ada: '1.0.4',
  ares: '1.19.0',
  brotli: '1.0.9',
  cldr: '42.0',
  icu: '72.1',
  llhttp: '8.1.0',
  modules: '111',
  napi: '8',
  nghttp2: '1.52.0',
  openssl: '1.1.1t',
  simdutf: '3.2.2',
  tz: '2022e',
  undici: '5.21.0',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.16',
  v8: '10.8.168.25-node.12',
  zlib: '1.2.11'
}

> doks-child-theme@0.5.0 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended darwin/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
```

**Comment by h-enk** [comment]
How do you deploy to Gitlab Pages?

See also https://github.com/h-enk/doks/discussions/184

**Comment by simonstumpf** [comment]
My pipeline job looks like this:

```
pages:
  stage: init
  image: node:latest
  script:
    - cd $CUSTOMER_DOCUMENTATION_DIRECTORY
    - npm ci
    - npm run build
    - mkdir ../public
    - cp -r public/* ../public
  artifacts:
    paths:
      - public
```


Since my site is in a subfolder of my git, i have to then copy the public directory to the root (maybe not the most elegant solution, but it works)

**Comment by simonstumpf** [comment]
I've now downloaded and analysed the output of the build. 

One thing I noticed, ist that on the start page (the index.html file in the root directory of the build), the image src is correct:
```
<div class="col-lg-12 text-center"><img src=https://site.pages.my-gitlab/my-space/logo.png
                            alt="logo" height=200>
```

However when looking into a rendered file in the docs directory, the image src is not correct:
```
                    <p><img class="img-fluid lazyload blur-up" src=https://site.pages.my-gitlab/gitlab.png
                            alt="Create Gitlab group"></p>
```

I can see that all images, which are in the static folder, get moved into the root directory (this includes also the docs images, which are also accessible when entering the correct url). 

Is my linking to the images not correct? It looks like this in the markdown files in the docs directory:
```
![Gitlab](gitlab.png)
```

**Comment by h-enk** [comment]
![Snag_342b6717](https://user-images.githubusercontent.com/3902872/233772832-88b003c9-908d-4bb6-9ce9-da2689bc5183.png)

Yes, confirmed. It looks like a bug in the `render-image.html` of `@hyas/images` 0.2.1 (see also https://github.com/gethyas/images/blob/v0.2.1/layouts/_default/_markup/render-image.html#L4)

Upgrading to `@hyas/images` 0.3.2 could possibly solve your issue (not tested).

**Comment by h-enk** [comment]
Note to self: test with Doks v1.0.0-alpha.1

**Comment by simonstumpf** [comment]
I've upgraded the `hyas/images` to 0.3.2. 

However if I execute now `npm run build` it throws the following error:
```
Start building sites … 
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended darwin/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
Error: Error building site: "/Users/user/git/bff/customer_documentation/content/docs/gitlab/gitlab-permissions.md:1:1": "/Users/user/git/bff/customer_documentation/node_modules/@hyas/images/layouts/_default/_markup/render-image.html:8:3": execute of template failed: template: _default/_markup/render-image.html:8:3: executing "_default/_markup/render-image.html" at <partial "lazyimg" $params>: error calling partial: "/Users/user/git/bff/customer_documentation/node_modules/@hyas/images/layouts/partials/lazyimg.html:33:29": execute of template failed: template: partials/lazyimg.html:33:29: executing "partials/lazyimg.html" at <resources.Get>: error calling Get: dirs not supported resource types: &{0xc001d5a600 0xc001d42280}
Total in 4553 ms

```

**Comment by h-enk** [comment]
Version 0.3.2 is set up completely differently than 0.2.1

Did you follow the setup and usage instructions in the (new) [README.md](https://github.com/gethyas/images#hyas-images)?

I will set up a migration guide soon

**Comment by h-enk** [comment]
If you could share your repo, I could have a closer look into your situation

**Comment by simonstumpf** [comment]
I've followed the instructions, but still no success. 

Even running the server with the upgraded version doesn't work:
```
➜  customer_documentation git:(main) ✗ npm run server

> doks-child-theme@0.5.0 server
> exec-bin node_modules/.bin/hugo/hugo server

Start building sites … 
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended darwin/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
Error: Error building site: "/Users/simonstumpf/private/git/doks-issue/customer_documentation/content/docs/gitlab/gitlab-permissions.md:1:1": "/Users/simonstumpf/private/git/doks-issue/customer_documentation/node_modules/@hyas/images/layouts/_default/_markup/render-image.html:8:3": execute of template failed: template: _default/_markup/render-image.html:8:3: executing "_default/_markup/render-image.html" at <partial "lazyimg" $params>: error calling partial: "/Users/simonstumpf/private/git/doks-issue/customer_documentation/node_modules/@hyas/images/layouts/partials/lazyimg.html:33:29": execute of template failed: template: partials/lazyimg.html:33:29: executing "partials/lazyimg.html" at <resources.Get>: error calling Get: dirs not supported resource types: &{0xc0015bbf80 0xc000be8640}
Built in 600 ms
```


I've copied the content to a public repository (with redacted content), so feel free to clone the repo if this helps you:
https://gitlab.com/simonstumpf/doks-issue/-/tree/main/customer_documentation

**Comment by h-enk** [comment]
Looks like the repo is private?

**Comment by h-enk** [comment]
Using `"@hyas/images": "^0.2.1",`

See: 

- https://gitlab.com/h-enk/doks-1048
- https://h-enk.gitlab.io/doks-1048/my-space/

Pay special attention to:

- https://gitlab.com/h-enk/doks-1048/-/blob/main/config/_default/module.toml#L69
- https://gitlab.com/h-enk/doks-1048/-/blob/main/layouts/_default/_markup/render-image.html#L4 (customization: `"getRelative" false`)

Bonus:

- https://gitlab.com/h-enk/doks-1048/-/blob/main/config/_default/config.toml#L11
- https://gitlab.com/h-enk/doks-1048/-/blob/main/.gitlab-ci.yml

**Comment by simonstumpf** [comment]
> Looks like the repo is private?

sorry about that, I've changed it

I'll have a closes look into your suggestions
