### ISSUE TITLE
No CSS with www prefix

### ISSUE THREAD

**Issue by StefanSalewski** [h-enk/doks#1049]
Dear Sir,

I just noticed a small issue with my recently created website

nimprogramming.com

All works fine, when the site is called without www prefix like
https://nimprogramming.com/. But when a www prefix is involved like
https://www.nimprogramming.com/ no CSS is used.

$ cat ./config/production/config.toml
canonifyURLs = false
baseURL = 'https://nimprogramming.com/'

For deploy, I use commands hugo and ./deploy as described in the Hugo tutorial.

At all-inkl.com I have as basedirectory

/www/htdocs/w01cb90a

and the website data is in nimprogramming.com/

I have currently no idea for the reason of the issue. Only idea is, that without setting baseURL I initially also had no CSS support.

**Comment by StefanSalewski** [comment]
This is the comment from all-inkl.com admin:

Hello,

thanks for your request.

I cannot detect any error on the server's side and all relevant setting (including DNS) of this domain are also correct. There's no .htaccess file with possible rewirte rules or anything like that which could cause the problem and there's also no issue with the configuration of the SSL certificate.

So there must be an issue with the internal path configuration of the website or CSS itself. The website doesn't use a database and it seems that you are not using an official CMS. In that case we cannot help you further and you should contact your web admin.

**Comment by StefanSalewski** [comment]
Well, with

$ cat ./config/production/config.toml
canonifyURLs = false
baseURL = 'https://www.nimprogramming.com/'

it is just the opposite, no CSS without www prefix. But still I do not understand it.

**Comment by StefanSalewski** [comment]
I hope this Google provided link may fix it:

https://discourse.gohugo.io/t/base-url-with-www-without-www/26498

Will report later, need a break now :-)

**Comment by h-enk** [comment]
Any reason why you want to provide both www and no www?

See also: [Www or no www? And what about duplicate content?](https://yoast.com/video/ask-yoast-use-www-or-not/)

**Comment by StefanSalewski** [comment]
Thank you for your fast reply.

I will study the link that you provided. I had the feeling, that most websites work with and without www prefix. But actually, I generally use links without www myself. Currently, for the nimprogramming.com site, we get the same content with and without www, but only one has nice CSS. So my fear would be, that some people would only try with www, see content without CSS, and think that it is a very simple page, and never try without www. Maybe showing an error with www would be an opttion. Well, I will study the link.

The solution suggested in the Hugo forum seems to be not that good, this is what all-inkl.com said:

Hello,

thanks for your request.

I have tested it. The rewrite rule doesn't work and then throws 500 Internal Server Error. And I also tried another, but a little different rewrite rule. That didn't gave me a 500 error, but it also didn't solve the issue which indicates that the cause of the error must be in your website's path configuration, otherwise the rewrite rule would work. And usually you don't need such rewrite rules, because a domain always works with and without www by default. You only need them to prevent Google from possibly recognizing duplicate content and/or to force redirection to one version of the URL, either with or without www.

**Comment by StefanSalewski** [comment]
From my understanding, a working redirect would be the correct solution? yoast.com seems to redirect as well when called with www. So I have to find out why the redirect solution in the hugo forum does not work, fix it, and use redirect?

**Comment by h-enk** [comment]
Yes, a redirect from www to apex (non www) domain or vice versa is what you should set up.

**Comment by StefanSalewski** [comment]
Thanks for that clarification. I assumed that, but was not sure. I have not yet been able to create a working redirect for all-inkl.com, I guess I have to ask there on monday again, when more experts are available.

**Comment by StefanSalewski** [comment]
>The rewrite rule doesn't work

Yes, I had a lot of trouble with rewrite rules found on Internet
myself. Then I finally found

https://all-inkl.com/wichtig/htaccessgenerator/

and with

"immer auf SSL und domainname.de"

it gave me this .htaccess:

cat public/.htaccess 

RewriteEngine On
RewriteCond %{HTTPS} off [OR]
RewriteCond %{HTTP_HOST} ^www\. [NC]
RewriteRule (.*) https://nimprogramming.com%{REQUEST_URI} [L,NE,R=301]

Together with

cat ./config/production/config.toml
canonifyURLs = false
baseURL = 'https://nimprogramming.com/'

it seems to work now. I had to clear the Firefox browser cache
manually, maybe corrupted browser cache was the reason why some
redirect code from Internet did not work.

Thanks for your support, Stefan Salewski
