### ISSUE TITLE
Add multiple 'docs' section and the possibility to rename them

### ISSUE THREAD

**Issue by Voralberg** [h-enk/doks#1058]
## Summary

As more or less shown in the original [Doks](https://getdoks.org/) website, could be added the possibility to have multiple 'docs' section, each one with the respective lateral panel submenus? And consequently the possibility to rename the 'docs' sections in arbitrary names?

### Basic example

Something similar in the original [Doks](https://getdoks.org/) website where both the Docs and Showcase section have each their own separate submenus.

### Motivation

This would greatly improve the structure of very extended websites with a lot of articles.

**Comment by h-enk** [comment]
That's where the `create` command comes in handy:

https://getdoks.org/docs/overview/commands/#docs-based-tree

**Comment by Voralberg** [comment]
> That's where the `create` command comes in handy:
> 
> https://getdoks.org/docs/overview/commands/#docs-based-tree

Well, then I apologize for opening this request. I thank you for this beautiful theme.

**Comment by binnyg** [comment]
We are able to create multiple docs sections but the sidebar is not working in the new docs section. Do we have to manually create the sidebar folder and code inside the layouts for the left navigation to work?

**Comment by h-enk** [comment]
See https://github.com/h-enk/doks/discussions/538#discussioncomment-6264981
