### ISSUE TITLE
Adding /* */ breaks search shortcut

### ISSUE THREAD

**Issue by vuphuctho** [h-enk/doks#1077]
## Description

When writing documentation for a .NET project, I have to use comment block `/* */` in markdown files. However, adding the text breaks shortcut for focusing search box.

### Steps to reproduce
- Follow [gudeline](https://getdoks.org/docs/tutorial/start-new-project/) to start new project using starter theme.
- After complete all the step in the guideline, modify any file by adding comment block `/* */`, e.g. `content/en/docs/prologue/introduction.md `

> add directly to .md file
> /* */
> 
> or add inside an inline code `/**/`
> 
> or add inside a code block
> ```
> /* */
> ```
### Expected result

Shortcut `Ctrl + /` should focus to the search box.

### Actual result

Shortcut doesn't work. In Chrome following error shows

```
Uncaught SyntaxError: Invalid or unexpected token (at index.js:88:330)
```

![image](https://github.com/h-enk/doks/assets/3623903/1fb027d7-8ec6-4538-80d5-aaff32ac7816)

### Environment

```
> @hyas/doks@0.5.0 precheck
> npm version

{
  '@hyas/doks': '0.5.0',
  npm: '8.19.2',
  node: '18.12.1',
  v8: '10.2.154.15-node.12',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.10',
  openssl: '3.0.7+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022b',
  unicode: '14.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}

> @hyas/doks@0.5.0 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.107.0-2221b5b30a285d01220a26a82305906ad3291880+extended linux/amd64 BuildDate=2022-11-24T13:59:45Z VendorInfo=gohugoio

```

**Comment by h-enk** [comment]
And if you use the HTML syntax?

```md
<!-- Write your comments here -->
```

**Comment by vuphuctho** [comment]
@h-enk  No issue with HTML syntax. I add using 3 ways listed above (directly to markdown, put inside inline code, put inside code block).

**Comment by vuphuctho** [comment]
@h-enk I think I misunderstood your comment. Do you mean putting /* */ inside the HTML syntax like so
```
<!-- /* Comment block */ -->
```
Above does not trigger any error.

**Comment by h-enk** [comment]
No, I meant like so:

```md
<!-- Comment block -->
```

**Comment by vuphuctho** [comment]
> No, I meant like so:
> 
> ```
> 
> ```

Adding above does not cause any issue.

**Comment by h-enk** [comment]
If I recall it correctly, your issue should be fixed when you delete these lines: https://github.com/h-enk/doks/blob/master/assets/js/index.js#L79-L93

Doks v1.0 (available soon) handles search smarter — you won't have this issue then.

**Comment by vuphuctho** [comment]
Thank you, the suggestion works.
