### ISSUE TITLE
Is full width still possible with Doks 1.0?

### ISSUE THREAD

**Issue by Yvand** [h-enk/doks#1091]
I'm upgrading my site to @hyas/doks-core 1.0.5.
One thing I cannot do is to show my site with full width.
This was introduced in https://github.com/h-enk/doks/pull/636

I tried to enable it in my `config/_default/hugo.toml` but it doesn't help:

```toml
[options]
  fullWidth = true
```

Am I doing something wrong?

Side note: your links in <https://github.com/h-enk/doks/issues/new/choose> are broken, so I had to open a blank issue.

**Comment by h-enk** [comment]
Fixed — see also  [@hyas/doks-core v1.0.6](https://github.com/gethyas/doks-core/releases/tag/v1.0.6)

1. In your project directory, run `npm i @hyas/doks-core@latest`
2. In `config/_default/hyas/doks.toml` set `containerBreakpoint = "fluid"`
3. In `config/_default/params.yml` add `mainSections: [docs]`

**Comment by Yvand** [comment]
Thank you, I tested and it works, but not as before:
The width of the text in the middle column did not increase.
More specifically, before:
![image](https://github.com/h-enk/doks/assets/8788631/b4ea44f3-7ec1-4725-bf68-662b760c54e8)

After:
![image](https://github.com/h-enk/doks/assets/8788631/d842f967-395a-415c-8f0b-f3d2f5462fdb)

My goal for the full width is that the extra space benefits mostly to the text in the middle column.
Can I apply a config to do this?

**Comment by h-enk** [comment]
Not a config setting (yet), but you can override the fixed width in your `_custom.scss`:

```scss
.container-fw {
  // max-width: 1200px;
  max-width: 100%;

  .docs-toc {
    margin-left: 3rem;
  }
}
```

**Comment by Yvand** [comment]
Ok, I created `assets/scss/_custom.scss` copied your content inside, deleted dir `resources/_gen/assets/scss`, ran `npm run dev` but it has no effect, I guess my scss is just not used.
Do I need to reference my new `_custom.scss` somewhere?
Sorry if I ask dumb questions, my knowledge on Hugo / UI design is very low

**Comment by h-enk** [comment]
In `config/_default/module.toml` make sure you have:

```toml

[[mounts]]
  source = "node_modules/@hyas/doks-core/assets"
  target = "assets"
  excludeFiles = "scss/common/_custom.scss"

**Comment by h-enk** [comment]
And `assets/scss/_custom.scss` s/b `assets/scss/common/_custom.scss`

**Comment by h-enk** [comment]
You've placed your `_custom.scss` in `assets/scss/`

But you should place it in `assets/scss/common/` to be picked up

**Comment by h-enk** [comment]
Also, in your `package.json` bump `"@hyas/doks-core": "^1.0.6"` to `"@hyas/doks-core": "^1.0.7"`

**Comment by Yvand** [comment]
Yes it uses it successfully now ! Thank you !
