### ISSUE TITLE
Bootstrap undefined variable error on fresh install

### ISSUE THREAD

**Issue by bigethan** [h-enk/doks#1092]
Hello! I'm installing doks for the first time and am running into an error that I can't quite sort out (I'm new to Hugo's pipeline processes / mount stuff, likely something I'm missing)

-  Node version is 20.5.1
-  NPM is 10.1.0 (same error with npm 9.8.0 as well

Going through the default setup of:
```
npm create hyas@latest -- --template doks
cd project_name
npm install
npm run dev
```

<details>
<summary>Gives me this error about an undefined bootstrap variable (I've added `--verbose` to the command)</summary>

```
[ ~/project_name]$ npm run dev
> project_name@0.0.0 dev
> exec-bin node_modules/.bin/hugo/hugo server --bind=0.0.0.0 --verbose --disableFastRender --baseURL=http://localhost --noHTTPCache

WARN  --verbose is deprecated and will be removed in a future release. use --logLevel info
Watching for changes in /Users/me/project_name/{config,content,i18n,node_modules,package.json,static,themes}
Watching for config changes in /me/project_name/config/_default, /Users/me/project_name/config/_default/hyas, /Users/me/project_name/config/_default/menus
Start building sites …
hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended darwin/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio

INFO  copy static: syncing static files to /
INFO  build: running step process duration 1.421547ms
INFO  build: running step assemble duration 4.235515ms
INFO  build: running step render duration 566.961223ms
INFO  build: running step postProcess duration 1.044299ms
Built in 575 ms
Error: error building site: TOCSS: failed to transform "scss/app.scss" (text/x-scss): "/Users/me/project_name/node_modules/bootstrap/scss/_root.scss:94:70": Undefined variable: "$mark-color".
```
</details>

I've also tried installing via the `npm create hyas@latest` command, and `template: doks` gives the same error

Though hyas does work with the `template: bootstrap -> variant: recommended plugins` options

Any help would be greatly appreciated!

**Comment by h-enk** [comment]
Confirmed. Fix will follow shortly

**Comment by h-enk** [comment]
Fixed — [latest packages](https://github.com/gethyas/hyas#packages)

Running `npm create hyas@latest` will ask you to install the latest version

**Comment by bigethan** [comment]
Thank you!
