### ISSUE TITLE
Upgrade to Bootstrap 5

### ISSUE THREAD

**Issue by h-enk** [h-enk/doks#111]
## Summary

- [Bootstrap 5 Beta 1](https://blog.getbootstrap.com/2020/12/07/bootstrap-5-beta-1/)

### Basic example

- [Hyas](https://gethyas.com/)

### Motivation

> With our first beta release of Bootstrap 5, we’re calling it on new features and breaking changes. 

- RTL support

**Comment by NicoHood** [comment]
What about using tailwind? I think this could perfectly fit for this theme:
https://tailwindcss.com/

**Comment by h-enk** [comment]
> What about using tailwind? I think this could perfectly fit for this theme:
> https://tailwindcss.com/

That would require a significant effort to migrate to. Upgrading to BS5 is way easier (and I'm a fan of Bootstrap).

But more importantly (for me), I'm not a big fan of Tailwind CSS. Here's why:
- [Why Tailwind Isn't for Me](https://dev.to/jaredcwhite/why-tailwind-isn-t-for-me-5c90)
- [Thoughts about Utility-First CSS Frameworks](https://markus.oberlehner.net/blog/thoughts-about-utility-first-css-frameworks/)

**Comment by NicoHood** [comment]
Thanks for sharing those two articles. I did not try Tailwindcss, but I will give it a go for my next project.
