### ISSUE TITLE
netlify command issue with URLs

### ISSUE THREAD

**Issue by teamcrisis** [h-enk/doks#126]
The order of [these commands](https://github.com/h-enk/doks/blob/master/netlify.toml#L10-L17) is giving me trouble when using `netlify-cli`

Changing to this resolved the issue:
```
[context.production]
  command = "hugo --gc --minify -b $URL && npm run build:functions"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
```

Netlify was printing out `--gc` as part of the URL path if the URL wasn't specified last.

**Comment by h-enk** [comment]
Fixed with 20bac2a25bcdb3156120afd0d1b6543c0235f3c7 + 9581fc4c44d2fdfe6b6093365fdbf5dcd2b869a2
