### ISSUE TITLE
Can't use arrow keys for scrolling

### ISSUE THREAD

**Issue by AsbjornOlling** [h-enk/doks#127]
## Description

When I open my own page built with doks (forked from commit ecc76bf), or 
doks.netlify.app (also as of commit ecc76bf), I can't use the arrow keys to scroll

### Steps to reproduce

1. Open doks.netlify.app (in firefox or chromium or qutebrowser on linux)
2. Press down arrow

### Expected result

I expect the page to scroll down by a little bit.

### Actual result

The dev console prints error: "Uncaught type error: Cannot read property "focus" of undefined at HTMLDocument.suggestionFocus"

**Comment by h-enk** [comment]
Will be fixed w/ https://github.com/h-enk/doks/issues/130 — see how it works out:  [getdoks.org](https://getdoks.org/docs/prologue/introduction/)

**Comment by h-enk** [comment]
Fixed w/ Doks [v0.3.4](https://github.com/h-enk/doks/releases/tag/v0.3.4)
