### ISSUE TITLE
Add Breadcrumb Navigation

### ISSUE THREAD

**Issue by NicoHood** [h-enk/doks#131]
## Summary

Add a Breadcrumb navigation (with microdata markup) to the top of the page.

### Basic example

* https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/
* https://www.docsy.dev/docs/adding-content/navigation/

### Motivation

It makes it easier to orientate through the site. Could be an optional thing.

**Comment by teamcrisis** [comment]
I'd prefer `json-ld` format as it's the general recommended format for schema

https://developers.google.com/search/docs/data-types/breadcrumb#json-ld

**Comment by NicoHood** [comment]
I remember that it was recommended to use microdata for breadcrumbs (and only for those). But I cannot find it anymore, so I guess it is obsolete, I dont know. Should be okay.

**Comment by h-enk** [comment]
> I'd prefer `json-ld` format as it's the generally recommended format for schema
> 
> https://developers.google.com/search/docs/data-types/breadcrumb#json-ld

That's already implemented — see lines 82..108: https://github.com/h-enk/doks/blob/master/layouts/partials/head/structured-data.html

**Comment by h-enk** [comment]
Will add breadcrumb navigation (with microdata markup) to the top of a documentation page — as an option. See also:
- https://gohugo.io/content-management/sections/#example-breadcrumb-navigation
- https://schema.org/BreadcrumbList
