### ISSUE TITLE
Add sub navigation to main menu

### ISSUE THREAD

**Issue by h-enk** [h-enk/doks#159]
## Summary

Add sub navigation (1 level deep) to navbar — as an option

### Basic example

![Snag_151535f9](https://user-images.githubusercontent.com/3902872/136525555-2d02bf69-5646-4a9f-9085-2c4c12a8d4ed.png)

![Snag_15155529](https://user-images.githubusercontent.com/3902872/136525572-5088eb8e-adba-4504-b988-9ed46b2c524c.png)

- https://getbootstrap.com/docs/5.0/components/navbar/#nav
- https://getbootstrap.com/docs/5.0/examples/navbars/

### Requirements

- UX in line with dropdown for multilingual mode (+ versioned documentation):

![versioned-docs-support](https://user-images.githubusercontent.com/3902872/136526250-9b43427b-3ecb-457c-906f-6de5f261a4e1.png)

### Issues

- Set structure in `./config/_default/menus/menus.en.toml`, and if, how?
- Relation w/ https://github.com/h-enk/doks/issues/497, how can these 2 work together?

### Motivation

https://github.com/h-enk/doks/discussions/464

**Comment by h-enk** [comment]
@lmas3009, thanks.

I preferably like to see the Bootstrap behavior mimicked  as much as possible — see https://getbootstrap.com/docs/5.0/examples/navbars/

So: 
- Add a [chevron-down](https://github.com/feathericons/feather/blob/master/icons/chevron-down.svg) on the right hand side of a dropdown link (so that it's super clear that there is a dropdown — on click).
- On small screens the dropdown should not overlay, but show in page

**Comment by lmas3009** [comment]
![image](https://user-images.githubusercontent.com/60876387/136547973-9dc4592e-f31b-45a2-ae83-36685c8362a2.png)
![image](https://user-images.githubusercontent.com/60876387/136548013-8db8b2f9-77dc-4a62-b18f-a747c146a9a7.png)

@h-enk now is this okay

**Comment by lmas3009** [comment]
> @lmas3009, large screens OK, for small screen I mean this:
> 
> ![1D785737-52AE-491A-A116-0DB4B43312E6](https://user-images.githubusercontent.com/3902872/136551405-ae2f67b6-2aea-41d2-8807-20c1d3d02205.GIF)

Okay i will try

**Comment by lmas3009** [comment]
Can i Raise a PR
