### ISSUE TITLE
Invisible text - in searchbar - in dark mode

### ISSUE THREAD

**Issue by sid-r-singh** [h-enk/doks#178]
## Description

The text typed inside search bar, in dark  mode is invisible

### Steps to reproduce

1. Go to https://getdoks.org/
2. Enable dark mode by clicking on the moon icon
3. Start typing anything in the search bar

### Expected result
The text being typed should be visible (should be white/light color).

### Actual result
The color of text was dark (possibly same as that of the dark background) & thus it was not visible.

### Environment
I am sorry, I don't have access to nodejs
OS: Windows
Browsers: Firefox, Edge

https://user-images.githubusercontent.com/68782815/111057456-bec93c80-84ad-11eb-858c-e46e10c39c77.mp4

**Comment by h-enk** [comment]
Confirmed — will fix. Thx

**Comment by h-enk** [comment]
Fixed with 57fee179f8b8ee0c45d90456703230e1e7edeb84

![Snag_9fb149](https://user-images.githubusercontent.com/3902872/111608697-cf452400-87d9-11eb-9468-46a12b123ccc.png)

See also: [doks.netlify.app](https://doks.netlify.app/)

N.B. Will also be fixed for [getdoks.org](https://getdoks.org/)

**Comment by sid-r-singh** [comment]
Awasome.
