### ISSUE TITLE
🚀 Support more language search with Fusejs

### ISSUE THREAD

**Issue by volfclub** [h-enk/doks#209]
## Summary

**Fusejs** supports more language search, such as Japanese, Chinese, Korean, etc. And it's very friendly with Hugo.

https://github.com/krisk/Fuse

### Basic example

https://github.com/onweru/compose/commit/c725994276ea22a1bf11e136eef4a5d41999f8cb

https://github.com/zzossig/hugo-theme-zzo/issues/28

https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae

### Motivation

Compared with algolia, fusejs is more flexible and convenient to use out of the box; compared with common solutions such as lunrjs, fusejs is more language friendly. Therefore, I think adding fusejs as an alternative can better search.

**Comment by h-enk** [comment]
I've added default language specific settings to the documentation for Latin, Arabic, Cyrilic + Indian, and CJK. See also: https://getdoks.org/docs/reference-guides/flexsearch/#language-settings

See also https://github.com/h-enk/doks/pull/208

**Comment by h-enk** [comment]
@volfclub, thanks for your input. Both FlexSearch and Algolia are great options for Hugo + Doks. That's why I am planning to add Algolia Search (next to FlexSearch) as an option. See also: https://github.com/h-enk/doks/issues/130
