### ISSUE TITLE
Disabling lazyLoad still uses placeholder image

### ISSUE THREAD

**Issue by TheTimeWalker** [h-enk/doks#252]
## Description

When disabling the lazy load feature via the params, the images are not shown directly with their normal sizes. Instead, the placeholder image is used and nothing happens at load.

### Steps to reproduce

1. Add in an img shortcode
2. Disable lazyLoad in params.toml

### Expected result

The normal image is loaded instantly without lazy loading applied

### Actual result

Placeholder image is used, and you see a blurred version of the image instead

![image](https://user-images.githubusercontent.com/8660693/115794650-a8789f80-a3ce-11eb-8922-62a42360d952.png)

### Environment

```json5
{
  'doks-child-theme': '0.2.3',
  npm: '6.14.4',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '36.1',
  icu: '66.1',
  llhttp: '2.0.4',
  modules: '79',
  napi: '6',
  nghttp2: '1.40.0',
  node: '13.14.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.37.0',
  v8: '7.9.317.25-node.32',
  zlib: '1.2.11'
}
```

**Comment by h-enk** [comment]
@TheTimeWalker, better late than never 😉 Fixed w/ f1fdec85de1d9f5d9fe5e0ae3b1ca560f0051295
