### ISSUE TITLE
Images do not load correctly if the site is hosted in a subfolder

### ISSUE THREAD

**Issue by TheTimeWalker** [h-enk/doks#253]
## Description

If the website is hosted in a subfolder, the images used with the img shortcode do not seem to take this in account and instead try to load from the root location ending with a 404 error. It doesn't matter if the baseUrl has been changed in the config.

### Steps to reproduce

1. Add in an img shortcode
2. Change the baseUrl to something with a subfolder (e.g. example.com/documentation)
3. Host the site in a subfolder

### Expected result

The image src is using the baseUrl with the subfolder and load correctly e.g.
`https://my-doc-site.com/documentation/ui-pages_hue0d2ad0362a4496ebe400446b0521ccf_22136_20x0_resize_box_2.png`

### Actual result

The image src directly relates to the domain and ignores the subfolder e.g.
`https://my-doc-site.com/ui-pages_hue0d2ad0362a4496ebe400446b0521ccf_22136_20x0_resize_box_2.png`

### Environment

```json5
{
  'doks-child-theme': '0.2.3',
  npm: '6.14.4',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '36.1',
  icu: '66.1',
  llhttp: '2.0.4',
  modules: '79',
  napi: '6',
  nghttp2: '1.40.0',
  node: '13.14.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.37.0',
  v8: '7.9.317.25-node.32',
  zlib: '1.2.11'
}
```

**Comment by h-enk** [comment]
See: https://github.com/h-enk/doks/discussions/249 + https://github.com/h-enk/doks/pull/238

**Comment by TheTimeWalker** [comment]
Thanks! I accidentally missed the discussion thread. Using the temporary workaround works like a charm - no extra config needed 😄

**Comment by h-enk** [comment]
Fixed w/ https://github.com/h-enk/doks/pull/238
