### ISSUE TITLE
FlexSearch result URL is broken when baseURL is set 

### ISSUE THREAD

**Issue by soichih** [h-enk/doks#268]
I just installed the latest version of doks and playing around with it. 

I have to release our site under some baseURL like (https://somewhere.com/somebase/). I've configured baseURL in `config/production/config.toml` like so

> baseurl = "https://somewhere.com/somebase/"

Everything works except when I search a page under FlexSearch bar, and when I click on the search result, it jumps to URL like `https://somewhere.com/docs/somepage` instead of `https://somewhere.com/somebase/docs/somepage` and user ends up with 404 error. 

I've tried to configure the baseURL for FlexSearch but I couldn't find such option. I am not sure if this is a bug with FlexSearch or Doks, or hugo itself, but how should I fix this?

**Comment by h-enk** [comment]
Hi, @soichih, in `./assets/js/index.js`, could you try replacing line 89: `href: "{{ .RelPermalink | relURL }}",` w/ `href: "{{ .Permalink | absURL }}",` and check  if that does the trick?

**Comment by soichih** [comment]
I've tried to the `absURL` filter, but I didn't notice any change to the behavior. 

Meanwhile, I've tried setting canonifyURLs to false in `config/production/config.toml` 

```
baseurl = "/dsla/"
canonifyURLs = false
```

This fixed the FlexSearch issue, but now my images are not displayed. I am doing the following which worked before..

```
![sample image](/images/sample.gif)
```

But now this seems to be looking at absolute path "https://somehost.com/images/sample.gif" instead of "https://somehost.com/dsla/images/sample.gif".

**Comment by soichih** [comment]
Sorry, please ignore my last post. I wasn't reading your suggestion correctly. I was doing

```
{{ .RelPermalink | relURL }}
```

instead of..

```
{{ .Permalink | absURL }}
```

Your suggestion fixed it, and now everything is working. Thank you @h-enk !

**Comment by NOBLES5E** [comment]
This needs to be fixed on master? @h-enk

**Comment by h-enk** [comment]
> This needs to be fixed on master? @h-enk

Yes, absolutely — I will do that (soon).

**Comment by h-enk** [comment]
1589916e5815e029038635f29dd7d2a983de35e7: changed to `href: "{{ .Permalink }}",`

**Comment by soichih** [comment]
I am setting baseurl in my production config.toml

[config/prduction/config.toml]

```
baseurl = "/projects/tla/"
canonifyURLs = true
```

I am not sure if it's related to this change, but I am using h-enk/doks-child-theme and after updating to the latest code in master branch, the baseURL gets repeated inside the URL like this.

```
/projects/tla/projects/tla/fonts/vendor/jost/jost-v4-latin-regular.woff2
```

I also noticed that double quotes around these URLs are missing.

For example, this is exactly what I see in index.html

```
<link rel=preload as=font href=/projects/tla/projects/tla/fonts/vendor/jost/jost-v4-latin-regular.woff2 type=font/woff2 crossorigin>
```

However, some URLs are correctly formatted.. Like these..

```
<meta property="og:image" content="/projects/tla/doks.png">
```

I don't know why some URLs are broken and some are not, but I just wanted to report this.
