### ISSUE TITLE
Unlimited docs, collapsible navigation and full width

### ISSUE THREAD

**Issue by naujoel** [h-enk/doks#290]
## Summary

Of course, Doks is a standout theme, but for me it lacks the ability to create unlimited docs and collapsible docs menu to be excellent. Today the documentation part seems to be aimed at websites with one or two few page tutorials, but imagine a website that wants to publish 20 books with three levels of subpages, the menu management through menus.toml would be difficult and prone to errors. In these cases it seems better to manage the menu of each book through front matter. The solution would be to be able to create documentation with hugo new --kind docs /new/book and in the main menu an item could list all the books to choose which one to navigate. I have been testing Doks for a couple of days because I wanted to use it in my new project, in fact I had already started to put content in my local installation, but I have been blocked by these problems. My computer skills do not go any further.

### Basic example

Collapsible book navigation example and full page width (If we are going to use the two side bars, why waste space? we need the full width): https://gohugo.io/documentation/

Unlimited docs: https://uniwebsidad.com/libros

### Motivation

I have tried some themes and chose Academic in my previous project, when Doks was not born yet, and I think I can say that there is no perfect theme, they all require computer skills to be able to adapt each solution. Dummys like me always have the same question, if I had enough computer knowledge to adapt a topic, would I choose to adapt it or would I directly make a new one?
Please excuse me for my English, it comes from translate

**Comment by h-enk** [comment]
Collapsible book navigation: fixed w/ Doks [v0.3.4](https://github.com/h-enk/doks/releases/tag/v0.3.4)

**Comment by h-enk** [comment]
- [x] Full width as an option — implemented w/ https://github.com/h-enk/doks/pull/636
- [x] Auto generated collapsibile section menu — implemented w/ https://github.com/h-enk/doks/pull/617
- [x] Three levels of subpages — implemented w/ https://github.com/h-enk/doks/pull/617
- [ ] Unlimited docs
