### ISSUE TITLE
[Feature] Open external sites in new tab

### ISSUE THREAD

**Issue by itsnotsaved** [h-enk/doks#294]
## Summary

https://github.com/h-enk/doks
https://github.com/h-enk/doks-child-theme
https://github.com/h-enk/getdoks.org

When open external domains contained in navbar buttons, in pages or homepage, footer etc those are open in same tab then it leave the origin site. i think it's not suitable then external links should open in new tab by default whether it contain as hyperlink, button or plain text link

### Basic example

eg: https://getdoks.org/
check navbar github buttons etc, home page and docs page external links and footer hugo etc links.

### Motivation

As mentioned and that'll be good for sites that create using docks and docks child site themes and for other readers come to the getdoks site.

**Comment by h-enk** [comment]
Hello @itsnotsaved, I've given this a lot of thought. Actually, in one of the initial versions of Doks external links were opening in a new tab. However, I decided against that, and reverted back to what I see is now current practice — in short: "leave the decision up to the visitor":

![Snag_13ad0c6](https://user-images.githubusercontent.com/3902872/118645133-d7700e80-b7de-11eb-9720-674ac85fc7cd.png)


## More background:
- [G200: Opening new windows and tabs from a link only when necessary](https://www.w3.org/TR/WCAG20-TECHS/G200.html)
- [When to Open Links in a New Tab](https://meiert.com/en/blog/links-in-new-tabs/)
- [Should external links open in a new tab or not?](https://belikewater.ca/blog/entry/linking-best-practice)
