### ISSUE TITLE
Typo in index.redirects: RelRelPermalink instead of RelPermalink

### ISSUE THREAD

**Issue by Yvand** [h-enk/doks#321]
## Description

I think there is a typo in file index.redirects, which prevents redirects to work (hugo fails to compile if an alias is created in any content markdown).
The content of the file is:

```
{{- range $p := .Site.Pages -}}
{{- range .Aliases }}
{{ . }} {{ $p.RelRelPermalink -}}
{{- end }}
{{- end -}}
```

I think `$p.RelRelPermalink` should be replaced with `$p.RelPermalink`.
As a workaround, I overwrote this file with its copy in the site directly, replaced the typo above, and now it works fine.

### Steps to reproduce

- Create a site using Doks template child theme
- Create a markdown in the content folder, and add an alias in the front matter, e.g.:

```
aliases:
  - /Install-LDAPCP.html
```

- Then start the server

### Expected result

Compilation works

### Actual result

Compilation fails

### Environment

```json
{
  'hugo-ldapcp': '0.1.0',
  npm: '6.14.13',
  ares: '1.17.1',
  brotli: '1.0.9',
  cldr: '38.1',
  icu: '68.2',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.0',
  openssl: '1.1.1k',
  tz: '2020d',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.63',
  zlib: '1.2.11'
}
```

**Comment by h-enk** [comment]
Fixed w/ 819cbc3ae8408cd1bf195149f9290542d90cb5e4
