### ISSUE TITLE
Toggling collapse sidebar triggers headers in text

### ISSUE THREAD

**Issue by sbarrios93** [h-enk/doks#377]
## Description

![CleanShot 2021-07-04 at 12 31 03](https://user-images.githubusercontent.com/19554889/124392520-17724e80-dcc4-11eb-8ea0-6ca10574c5a9.gif)

### Steps to reproduce

See the GIF Above

**Comment by h-enk** [comment]
@sbarrios93, thanks. Will be looking into it.
