### ISSUE TITLE
hugo-installer fails behind proxy

### ISSUE THREAD

**Issue by OCram85** [h-enk/doks#393]
## Description

After upgrading to recent doks 0.3.3 version I noticed some npm install errors in my dev workstation and ci/cd pipeline:

### Steps to reproduce

run `npm install` with recent doks version on system behind a corporate proxy.

### Expected result

... Should install all required node modules

### Actual result

![image](https://user-images.githubusercontent.com/13993700/126308934-ef9d974a-4d65-43fa-886c-9d9e7c4a5231.png)

### Environment

Paste the information here as shown by `npm run check`

### 📓  Debugging notes

- ❓  The hugo-installer uses [got](https://github.com/sindresorhus/got) for http requests. I'm not sure if it respects the systems `http_proxy`  env or npm proxy config. Does anyone else have this problem behind a proxy? - Maybe there is an issue with the proxy itself 😀 

- ❓  Could we switch back to the `hugo-bin` package?

### 🔖 Refs

- https://github.com/dominique-mueller/hugo-installer/discussions/37

**Comment by OCram85** [comment]
@h-enk : maybe it's worth looking at [hugo-extended](/jakejarvis/hugo-extended). It seems to fix the hugo-bin package while reflecting hugo versioning.

**Comment by h-enk** [comment]
> Could we switch back to the hugo-bin package?

No, the main reason for switching to [hugo-installer](https://github.com/dominique-mueller/hugo-installer), is that hugo-bin introduced 6 high severity vulnerabilities that will not be fixed any time soon — see also: https://github.com/fenneclab/hugo-bin/issues/114. Aside from that, what I like a lot about hugo-installer is that it verifies the checksum + runs a health check when installing.

**Comment by h-enk** [comment]
@OCram85, I guess this would help you indeed: https://github.com/dominique-mueller/hugo-installer/discussions/37#discussioncomment-1032541

**Comment by OCram85** [comment]
> @OCram85, I guess this would help you indeed: [dominique-mueller/hugo-installer#37 (comment)](https://github.com/dominique-mueller/hugo-installer/discussions/37#discussioncomment-1032541)

I hope so. Just found your conversation at https://github.com/fenneclab/hugo-bin/issues/114 which helps me understanding a lot 👯

**Comment by h-enk** [comment]
@OCram85, see https://github.com/dominique-mueller/hugo-installer/pull/38 + https://github.com/dominique-mueller/hugo-installer/discussions/37#discussioncomment-1042292

Curious if it works for you.

**Comment by OCram85** [comment]
> @OCram85, see [dominique-mueller/hugo-installer#38](https://github.com/dominique-mueller/hugo-installer/pull/38) + [dominique-mueller/hugo-installer#37 (reply in thread)](https://github.com/dominique-mueller/hugo-installer/discussions/37#discussioncomment-1042292)
> 
> Curious if it works for you.

Works perfect with `hugo-installer >= 3.1.0`
