### ISSUE TITLE
copyRight is not shown in the default footer (or anywhere else)

### ISSUE THREAD

**Issue by rslifka** [h-enk/doks#420]
There is a `copyRight` set in `params.toml` however it never makes its way in to the footer.

From a [search in the Doks repo](https://github.com/h-enk/doks/search?q=copyRight), it doesn't appear to be referenced anywhere.

Presumably this is meant to be inserted adjacent to the Privacy / Code of Conduct links in the footer?

**Comment by h-enk** [comment]
@rslifka, thanks for pointing this out. Actually, `copyRight` was meant to make its way to `./layouts/rss.xml`: https://github.com/h-enk/doks/blob/master/layouts/rss.xml#L10-L11

You could use `footer` for a copyright notice in the footer.

Fixed w/ f4aece8e5df3a0bfb2c33042d19881b6ec2becdf: https://doks.netlify.app/index.xml
