### ISSUE TITLE
unable to launch doks on github.io

### ISSUE THREAD

**Issue by solo10010** [h-enk/doks#473]
I tried everything I did according to the instructions
1. https://getdoks.org/docs/recipes/deployment/#deploy-to-github-pages
and
2. https://github.com/h-enk/doks-gh-pages

I did exactly according to the instructions but I have already passed not to go out(

my repository with doks https://github.com/solo10010/solo10010.github.io
my pages https://solo10010.github.io/

**Comment by h-enk** [comment]
Hi @solo10010, I cloned your repo, and tried to make it work. Because you're using the child theme, I had to comment out the test script in the workflow file — it (correctly) triggered an [error](https://github.com/h-enk/solo10010.github.io/runs/3708350935?check_suite_focus=true) — like so:

```yml
..
#      - name: Check for linting errors
#        run: npm test
..
```

Then it worked — see also (temporary available, until you're good):
- https://github.com/h-enk/solo10010.github.io
- https://h-enk.github.io/solo10010.github.io/

P.S. I noticed you're [workflow](https://github.com/solo10010/solo10010.github.io/actions/workflows/gh-pages.yml) did not run at all (I don't know why?).

**Comment by solo10010** [comment]
Hello @h-enk, thank you very much!!
yes, I coped with the problem by fork the repository you created for me.

the problem really turned out to be that for some reason the "Workflows" did not start, I tried to reinstall the theme according to the instructions, only changing the file, commenting out the lines of the test script that caused the error, but it did not work... the workflows never started.

then I just fork your repository for me via the web interface https://github.com/h-enk/solo10010.github.io
1. then I cloned "git clone" to my computer https://github.com/solo10010/solo10010.github.io"
2. changed the configs for myself "baseurl =" https://solo10010.github.io/ "
3. I deleted the repository fork via the web interface
4. created a new repository with the same name "https://github.com/solo10010/solo10010.github.io "
5. I filled all the files into a new empty repository "git push"
6. https://github.com/solo10010/solo10010.github.io

it worked!

P.S. I noticed you're workflow did not run at all (I don't know why?).

I also don't know why my workflows don't start.. although they were launched with other themes by hugo and Jekyll, but your theme is the best!!
and very suitable for my tasks Thank you for your attention.

**Comment by HarshadRanganathan** [comment]
> Hello @h-enk, thank you very much!! yes, I coped with the problem by fork the repository you created for me.
> 
> the problem really turned out to be that for some reason the "Workflows" did not start, I tried to reinstall the theme according to the instructions, only changing the file, commenting out the lines of the test script that caused the error, but it did not work... the workflows never started.
> 
> then I just fork your repository for me via the web interface https://github.com/h-enk/solo10010.github.io
> 
> 1. then I cloned "git clone" to my computer https://github.com/solo10010/solo10010.github.io"
> 2. changed the configs for myself "baseurl =" https://solo10010.github.io/ "
> 3. I deleted the repository fork via the web interface
> 4. created a new repository with the same name "https://github.com/solo10010/solo10010.github.io "
> 5. I filled all the files into a new empty repository "git push"
> 6. https://github.com/solo10010/solo10010.github.io
> 
> it worked! https://solo10010.github.io/
> 
> P.S. I noticed you're workflow did not run at all (I don't know why?).
> 
> I also don't know why my workflows don't start.. although they were launched with other themes by hugo and Jekyll, but your theme is the best!! and very suitable for my tasks Thank you for your attention.

In my case, the branch was `main` instead of `master` so the workflow never triggered. Changing the branch in the CI script triggered the workflow.
