### ISSUE TITLE
Vimeo tag blocked upon deploy to Netlify

### ISSUE THREAD

**Issue by drwilkins** [h-enk/doks#507]
## Description

When I embed a vimeo video using the Hugo shortcode, it works locally, but says it's blocked on the live website.

### Steps to reproduce
add `{{< vimeo id="146022717"  style="width: 100vw" title="My vimeo video" >}}` to example blog post

### Expected result
![image](https://user-images.githubusercontent.com/6098768/136988138-3c1d2fe6-eca0-43ad-89fe-c63c5a399e46.png)

### Actual result
![image](https://user-images.githubusercontent.com/6098768/136988177-395f90ce-1722-450c-ae4e-b5270ea0a76e.png)

### Environment
```
> doks-child-theme@0.3.5 precheck
> npm version

{
  'doks-child-theme': '0.3.5',
  npm: '8.0.0',
  node: '16.11.0',
  v8: '9.4.146.19-node.13',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

> doks-child-theme@0.3.5 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.88.1-5BC54738+extended darwin/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
```

Youtube tag (e.g. `{{< youtube id="w0HgHet0sxg">}}`) has same issue.

**Comment by h-enk** [comment]
That's intended 😉

1. Copy `./node_modules/@hyas/doks/layouts/index.headers` to `./layouts/`, and
2. In `./layouts/index.headers`, update your Content Security Policy to allow for `frame-src https://player.vimeo.com https://www.youtube.com;`, like so:

```bash
/*
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  Content-Security-Policy: default-src 'self'; frame-ancestors https://jamstackthemes.dev; manifest-src 'self' https://*.netlify.app; connect-src 'self' https://*.netlify.app; font-src 'self' https://*.netlify.app; frame-src https://player.vimeo.com https://www.youtube.com; img-src 'self' https://*.netlify.app data:; script-src 'self' https://*.netlify.app 'sha512-RBYr6Ld4w1yVqaACrgrBLQfPgGhj/1jyacA74WxJ1KM6KVcSWymwrdDwb3HDcdpwiNJ5yssot1He0U9vXoQVlg=='; style-src 'self' https://*.netlify.app 'unsafe-inline'
  X-Frame-Options: SAMEORIGIN
  Referrer-Policy: strict-origin
  Feature-Policy: geolocation 'self'
  Cache-Control: public, max-age=31536000
  Access-Control-Allow-Origin: *
```

P.S. 1) When something's not working, in Google Chrome or Firefox you can open Developer Tools (<kbd>F12</kbd>), go to the Console tab, and get some hints about what's wrong.

![Snag_4d8b093](https://user-images.githubusercontent.com/3902872/137341923-d9e44356-58b2-4f24-b9b9-dd1325e0a685.png)


P.S. 2) What to put in the Content Security Policy? [Laboratory](https://addons.mozilla.org/en-US/firefox/addon/laboratory-by-mozilla/) is an experimental Firefox extension that helps you generate a Content Security Policy (CSP) header for your website.
