### ISSUE TITLE
No feedback on no search results

### ISSUE THREAD

**Issue by h-enk** [h-enk/doks#514]
## Description

When there are no search results, no feedback message is displayed.

### Steps to reproduce

1. Browse to https://doks.netlify.app/docs/prologue/introduction/
2. Search for `22`
3. Hit <kbd>Enter</kbd>

### Expected result

Something like:

![Snag_30638fd](https://user-images.githubusercontent.com/3902872/137441433-44e21430-c39d-404c-a126-f55703e902d7.png)

### Actual result

No results:

![Snag_303f40e](https://user-images.githubusercontent.com/3902872/137441227-89c4e4c5-3e3f-4c6a-800c-cdda5ac64b12.png)

After hitting <kbd>Enter</kbd>:

![Snag_30404d7](https://user-images.githubusercontent.com/3902872/137441234-c2e6b18a-3960-4532-838f-ac8b7c6c6637.png)

### Environment

Not relevant.

**Comment by schnerring** [comment]
Algolia suggests search terms that people often search for. [From the Algolia docs](https://www.algolia.com/doc/ui-libraries/autocomplete/guides/adding-suggested-searches/): 

> The most common autocomplete UX is one that displays a list of suggested searches that your users can select from as they type. Algolia provides a Query Suggestions feature that generates suggested search terms based on your what your users are searching for and the results within your dataset.

Although flexsearch provides query suggestions, what you're looking for here is (user-)data-driven query suggestions which is typically done with analytics services.
