### ISSUE TITLE
Upgrade to 0.3.5 causes nil pointer in render-image.html 

### ISSUE THREAD

**Issue by stephen-masters** [h-enk/doks#535]
## Description

After upgrading to 0.3.5, the build crashes with the following error:

```
ERROR 2021/10/30 08:31:00 "/Users/stevie/dev/gowork/src/github.com/gratiartis/stephen-masters.github.io/node_modules/@hyas/doks/layouts/_default/_markup/render-image.html:3:18": execute of template failed: template: _default/_markup/render-image.html:3:18: executing "_default/_markup/render-image.html" at <$image.Resize>: nil pointer evaluating resource.Resource.Resize
```

This happens if any page in the site has an image link which is incorrect.

### Steps to reproduce

Add the following image short code to `_index.md`:

```
![Text](a-non-existent-image.png "The title of the non-existent image")
```

The build will break with no information as to why. The following is an example:

https://github.com/stephen-masters/doks/tree/bugfix/0.3.5-build-breaks-for-bad-image-links

### Expected result

The project should build.

### Actual result

`ERROR 2021/10/30 08:31:00 "/Users/stevie/dev/gowork/src/github.com/gratiartis/stephen-masters.github.io/node_modules/@hyas/doks/layouts/_default/_markup/render-image.html:3:18": execute of template failed: template: _default/_markup/render-image.html:3:18: executing "_default/_markup/render-image.html" at <$image.Resize>: nil pointer evaluating resource.Resource.Resize`

### Environment

```
> @hyas/doks@0.3.5 precheck
> npm version

{
  '@hyas/doks': '0.3.5',
  npm: '7.21.0',
  node: '16.6.2',
  v8: '9.2.230.21-node.19',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '93',
  nghttp2: '1.44.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}

> @hyas/doks@0.3.5 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.88.1-5BC54738+extended darwin/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
```

### Diagnosis

0.3.5 introduced a new template: `layouts/_default/markup/render-image.html`

This seems to be caused because the first line of the new template has `.Page.Resources.GetMatch .Destination`, which does not find an image in the resources for a page. This applies to any page in the whole site which has a broken link.

It can be fixed by wrapping the subsequent lines in:

```
{{ with $image }}

{{ else }}
<img src="{{ .Destination | safeURL }}"  alt="{{ $.Text }}" />
{{ end }}
```

**Comment by h-enk** [comment]
Please see: https://github.com/h-enk/doks/pull/536
