### ISSUE TITLE
Search function not working in second docs page

### ISSUE THREAD

**Issue by xbufu** [h-enk/doks#546]
### Discussed in https://github.com/h-enk/doks/discussions/543

<div type='discussions-op-text'>

<sup>Originally posted by **xbufu** November  3, 2021</sup>
Hi!

I am trying to create a second docs page, e.g. called `docs`, that should have the same layout as the `docs` page. I managed to do this by following [this](https://github.com/h-enk/doks/discussions/173) discussion topic. I managed to add the second page, all with correct menu entries and the sidebar showing correctly. I have also managed to get the search bar to appear correctly now, by adding the appropriate entries in `/layouts/partials/header/header.html`.

My problem has now become that the search does not return any results. There are no suggestions showing up while I type and when I hit enter it just reloads the page.

So far I have not found the reason for this. Can anyone help me fix it? I have published the source code here: https://github.com/xbufu/wiki.git and published them here: https://wiki.bufu-sec.com/</div>

**Comment by h-enk** [comment]
https://github.com/h-enk/doks/discussions/543 is the place to have this discussion
