### ISSUE TITLE
Text in copy button is searchable when hidden

### ISSUE THREAD

**Issue by santigz** [h-enk/doks#561]
## Description

The button to copy code blocks modifies its visibility by changing its opacity value from 0 to 1.
Therefore if the you search "copy" in the browser, the button will be searchable but invisible to the user, which is confusing.

Maybe set it to `display: none` when hidden?

### Steps to reproduce

Open a page with code blocks and use the browser to search "copy".

### Expected result

Invisible text should not be searchable.

### Actual result

The text within copy buttons is searchable even when invisible.

### Environment

Latest Doks.

**Comment by h-enk** [comment]
Hi, a little late, but I can reproduce this in Firefox (but not in Chrome).

However, will be fixed in the upcoming release of Doks.

**Comment by h-enk** [comment]
FIxed with visibility (more appropriate, I think) — see also the Bootstrap docs: [Visibility](https://getbootstrap.com/docs/5.1/utilities/visibility/)

8fcd777a2d7e4d8c38c72a06d31c83b179e90ca1
