### ISSUE TITLE
Sub Sub Menu

### ISSUE THREAD

**Issue by xyz-mtl** [h-enk/doks#573]
Hi,
I would like to have multiples sub menu in this theme like
- Topic 1
- Topic 2
-- 	Topic2 > Epic 2
--	Topic2 > Epic 2 > Story1
How to do it?

**Comment by h-enk** [comment]
Like this: https://codingnconcepts.com/hugo/nested-menu-hugo/

Will be part of one of the upcoming releases of Doks.

**Comment by nk9** [comment]
This would be great, I'd like to use this feature as well. Thanks Henk!
