### ISSUE TITLE
unable to access 'https://github.com/h-enk/doks.git/'

### ISSUE THREAD

**Issue by mahdiarsadeghi** [h-enk/doks#580]
Trying to clone doks repository to a directory with the command 

`git clone https://github.com/h-enk/doks.git docs` 

and the following error pups up:

`fatal: unable to access 'https://github.com/h-enk/doks.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443`

**Comment by h-enk** [comment]
Hmm, I can't reproduce this error (it works for me).

No related incident either — see https://www.githubstatus.com

Does this work for you:

```bash
git clone git@github.com:h-enk/doks.git doks-580
```
