### ISSUE TITLE
Dark mode button doesn't work on iPhone and iPad

### ISSUE THREAD

**Issue by bulinc** [h-enk/doks#624]
## Description

Dark mode button doesn't work on iPhone and iPad

### Environment

test getdoks.org  or   doks.netlify.app

**Comment by h-enk** [comment]
Cannot reproduce your issue.

It works for me on e.g.:

- iPhone 13, iOS v15.0, Chrome latest
- iPhone 12, iOS v14.1, Safari latest

What iPhone/iPad version (+ iOS version + browser) are you seeing the issue on?

**Comment by bulinc** [comment]
My device is:
iPhone 6 Plus iOS12.5.5 Safari 
iPad  iOS12.1 Safari
If the latest version is normal and the compatibility with the old version is not cost-effective, then I have no problem.
