### ISSUE TITLE
 left menu is collapsible

### ISSUE THREAD

**Issue by bulinc** [h-enk/doks#625]
## Summary

The entire menu area on the left is collapsible

### Basic example

[Include a basic example or links here.](https://docusaurus.io/docs/)

### Motivation

After the entire menu on the left is collapsed, the reading experience of the text content is better

**Comment by h-enk** [comment]
Current Doks behaviour is when viewing a page, only the parent section it belongs to is open:

![Snag_200e0c69](https://user-images.githubusercontent.com/3902872/150785200-bb5b6751-d13d-473f-8f1e-1dab52122ae9.png)

Not sure what you mean, could you elaborate some more /show a visual of what you mean?

**Comment by h-enk** [comment]
Do you mean this functionality:

![Snag_20121f90](https://user-images.githubusercontent.com/3902872/150785801-d457485d-f102-4705-b0bc-0ad5d158588b.png)

**Comment by bulinc** [comment]
> Do you mean this functionality:
> 
> ![Snag_20121f90](https://user-images.githubusercontent.com/3902872/150785801-d457485d-f102-4705-b0bc-0ad5d158588b.png)

yes,this function

**Comment by h-enk** [comment]
I see what you mean, but I don't think it will improve the reading experience of the main content.

Also, this is not common practice for documentation websites (only Docusaurus has implemented this, as far as I know)
