### ISSUE TITLE
Add custom scss file

### ISSUE THREAD

**Issue by h-enk** [h-enk/doks#655]
## Summary

Add custom scss file.

### Basic example

Include a basic example or links here.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

See e.g.: https://github.com/h-enk/doks/discussions/577#discussioncomment-1840823 + https://github.com/h-enk/doks/discussions/591

**Comment by assayire** [comment]
@nk9 Should the `layouts/partials/head/head.html` be created in the repo I create when creating the child theme (as described [**here**](https://github.com/h-enk/doks#doks-child-theme))?

The only other place I see a head.html is inside `node_modules\@hyas\doks\...` which does not seem to be the right place to make these changes. Appreciate your help.

**Comment by h-enk** [comment]
Now part of Doks Child Theme [v0.4.1](https://github.com/h-enk/doks-child-theme/releases/tag/v0.4.1) — adds files for [custom scss](https://github.com/h-enk/doks-child-theme/blob/master/assets/scss/common/_custom.scss) and [custom js](https://github.com/h-enk/doks-child-theme/blob/master/assets/js/app.js) (implemented w/ [12bf689da853e90ed51f25b8103e7beca68c23b0](https://github.com/h-enk/doks-child-theme/commit/12bf689da853e90ed51f25b8103e7beca68c23b0))
