### ISSUE TITLE
Contributor names in Blog keeps getting added with "and"

### ISSUE THREAD

**Issue by iamsantanubanerjee** [h-enk/doks#678]
## Description

The names of contributors in the Blog section keeps getting added with "and"

### Steps to reproduce

Add more than two contributor name in the "index.md" file of any blog

### Expected result

The names should be seperated by "," and not by an "and", except between the last, and the last but one name

### Actual result

![Screenshot 2022-02-17 215710](https://user-images.githubusercontent.com/59969215/154527177-3f2ab635-c275-4491-b37a-a4424a79c522.png)

### Environment

> @hyas/doks@0.4.0 precheck
> npm version

{
  '@hyas/doks': '0.4.0',
  npm: '8.3.1',
  node: '16.14.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1m+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

> @hyas/doks@0.4.0 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.92.1-85E2E862+extended linux/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio

**Comment by h-enk** [comment]
Thanks for reporting this issue. Will be addressed.
