### ISSUE TITLE
Better mobile navigation UX

### ISSUE THREAD

**Issue by h-enk** [h-enk/doks#68]
## Summary

Make the left sidebar navigation available on top, and consider also making the TOC navigation available on top.

### Basic example

![2021-01-05_09-00-32](https://user-images.githubusercontent.com/3902872/103624823-610ef600-4f3a-11eb-8d24-b0e3d023ad32.png)

See also:
- the new Gatsby Docs: https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/ and
- the new Bootstrap 5 Docs: https://getbootstrap.com/docs/5.0/getting-started/introduction/

### Motivation

Now, a user has to scroll to the bottom of a page to navigate to another documentation page.

See also: #65

**Comment by NicoHood** [comment]
I want to add a few more examples, that I like:
* https://tailwindcss.com/docs/extracting-components
* https://www.docsy.dev/docs/

**Comment by teamcrisis** [comment]
Another example: https://forestry.io/docs/welcome/

I think my favorite is the bootstrap example. I like that the left sidebar navigation gets collapsed to the top and the right TOC section gets added inline to the content. 

Many themes either hide these on mobile devices or shove them to the bottom of the page. Both of which are important navigational aids on mobile, so they should be kept closer to the top (but collapsed).

**Comment by h-enk** [comment]
https://github.com/h-enk/doks/releases/tag/v0.3.4
