### ISSUE TITLE
Inconsistency in UI

### ISSUE THREAD

**Issue by iamsantanubanerjee** [h-enk/doks#682]
## Description

Language dropdown doesn't change theme

### Steps to reproduce

Toggle multilingualMode to "true" in params.toml file

### Expected result

The dropdown should be dark with the dark theme

### Actual result

![ss](https://user-images.githubusercontent.com/59969215/154708526-c449e217-7dba-4ffc-984d-b727063e78ac.png)

### Environment

> @hyas/doks@0.4.0 precheck
> npm version

{
  '@hyas/doks': '0.4.0',
  npm: '8.3.1',
  node: '16.14.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1m+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

> @hyas/doks@0.4.0 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.92.1-85E2E862+extended linux/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio

**Comment by h-enk** [comment]
Thanks for reporting this issue. Will be addressed.

**Comment by h-enk** [comment]
![Snag_3c9e17d](https://user-images.githubusercontent.com/3902872/160803892-6ebc5d73-4359-49e5-8497-0f0e596a329e.png)

Fixed with 20eb2a22fda914726067c4e5c0b8b79d9ab5b4ec
