### ISSUE TITLE
How can we create and manage custom taxonomies for all content types. 

### ISSUE THREAD

**Issue by adarshdli** [h-enk/doks#692]
## Summary

I can see "contributor" tag appearing for blog posts. What I would like to see is similar mechanism to add more custom taxonomies across the site including docs. 

### Basic example

[antora-default-ui-hugo-theme](https://antora-default-ui-hugo-theme.netlify.app/).

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by h-enk** [comment]
Categories and tags for blog pages will be covered with https://github.com/h-enk/doks/issues/501

I don't think categories and tags (or other taxonomies) for documentation pages is what I would want for Doks. I think (sub)sections are more appropriate (see e.g. the [Gatsby docs](https://www.gatsbyjs.com/docs/how-to/local-development/)) — and that's covered for with [Doks v0.4.0](https://github.com/h-enk/doks/releases/tag/v0.4.0)
