### ISSUE TITLE
Video not showing anymore

### ISSUE THREAD

**Issue by ImaCrea** [h-enk/doks#700]
## Description

Suddenly videos are not showing anymore.

### Steps to reproduce

Go to a page where a video should be displayed.

### Expected result

Video player should show and we should be able to play it.

### Actual result

No player showing.

### Environment

Tested on various browsers Firefox, Safari, Chrome, all with latest update.

Live doc there https://aide.test-meteo.liiib.re/docs/essentiel-video/parametrer-son-profil/

You can see in the source the video tag, file is available, and still no player showing. It's very surprising as we didn't change anything meanwhile. Is this due to a new security or something ?

Any clue that could help understand what cause this issue so I can fix it is very appreciated :)

**Comment by ImaCrea** [comment]
Ah. I see that it's working when I'm testing on local environment (with remote url for videos) but not on the live version. Could that be a new security ?

**Comment by ImaCrea** [comment]
Something else, if I fix the height of the player in the css then the player is displayed.

![Capture d’écran 2022-03-08 à 10 40 16](https://user-images.githubusercontent.com/764332/157210253-287efe44-ded1-40ec-b397-b4fc00b3c326.png)

**Comment by h-enk** [comment]
Hmm strange, I cannot reproduce your error (no console log errors, tested on Windows with Chrome, Firefox, and Edge — all latest versions). Could it be a blocker preventing the video to show?

![Snag_14585436](https://user-images.githubusercontent.com/3902872/157306785-94481989-13ab-404f-bc1a-880e41ccae75.png)

**Comment by ImaCrea** [comment]
yes yes the video  is now showing because I forced height:500px in custom css. 

without it, it won't show the player when published online (local is ok weirdly)

**Comment by h-enk** [comment]
> without it, it won't show the player when published online (local is ok weirdly)

Then it might have something to do with your settings in `./config/postcss.config.js` or `./layouts/index.headers` (check console for errors).

Cannot reproduce this with a fresh install (it's working for me):

![Snag_10e36483](https://user-images.githubusercontent.com/3902872/159124246-84233497-575c-4125-bf95-63015307676d.png)
![Snag_10e37329](https://user-images.githubusercontent.com/3902872/159124251-444b02ba-dcb7-4d2d-82c2-ff240a77766d.png)
