### ISSUE TITLE
image-not-found

### ISSUE THREAD

**Issue by dcbuild3r** [h-enk/doks#702]
## Description

I am following the [documentation](https://getdoks.org/tutorial/add-images/) for adding images and when I reference an image I have inside of a folder inside of a markdown file and try to build the hugo app it gives me an image-not-found error. I've tried relative and absolute paths for the image, the error is not descriptive whatsoever, I've even tried a clean copy of the starter theme and it doesn't work there either.

### Steps to reproduce

Download and yarn install my-doks-site starter theme, go to docs, add image to any folder representing a section, create a markdown file and reference the image per the documentation -> Error image-not-found

### Expected result

The website should build and the website should show.

### Actual result

Error image-not-found

**Comment by wangpengliang815** [comment]
I have the same problem.

**Comment by ajdeve** [comment]
I have the same problem as well.

**Comment by h-enk** [comment]
Confirmed and looking into it

**Comment by dcbuild3r** [comment]
Doesn't work for me with exactly that. I have to host the images elsewhere and reference them via their image address link.

**Comment by dcbuild3r** [comment]
So here is where I'm trying to implement it, and doing exactly what you say above in my docs pages results in image-not-found errors. [devpill.me GitHub](https://github.com/dcbuild3r/devpill.me)

**Comment by wenyaoleoliu** [comment]
This issue is fatal. I tried a lot and think myself kind of familiar with Hugo. Even that, the images allowed in doks docs only allow images in a [page bundle](https://gohugo.io/content-management/page-bundles/).
