### ISSUE TITLE
Auto Collapse Menu Not Ordered by Weight

### ISSUE THREAD

**Issue by james-d-elliott** [h-enk/doks#709]
## Description

The auto-collapsible-menu.html layout does not honor the menu weight. I have also observed some other strange issues with the menu's but plan on producing some PR's and/or reproducing the issues I can't figure out how to fix.

### Steps to reproduce

1. git clone git@github.com:h-enk/doks.git
2. git checkout v0.4.0
3. Apply patch 1.
4. Observe no change in the menu order.
5. Apply patch 2.
6. Observe change in menu order.
7. Revert patch 1.
8. Observe change in menu order.

Patch 1:

```diff
Index: config/_default/menus/menus.en.toml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/config/_default/menus/menus.en.toml b/config/_default/menus/menus.en.toml
--- a/config/_default/menus/menus.en.toml	(revision e3fdbaa25905ee48825cd274272ea4b6069aea36)
+++ b/config/_default/menus/menus.en.toml	(date 1647783338753)
@@ -1,6 +1,6 @@
 [[docs]]
   name = "Prologue"
-  weight = 10
+  weight = 9001
   identifier = "prologue"
   url = "/docs/prologue/"
```

Patch 2:

```diff
Index: config/_default/params.toml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/config/_default/params.toml b/config/_default/params.toml
--- a/config/_default/params.toml	(revision e3fdbaa25905ee48825cd274272ea4b6069aea36)
+++ b/config/_default/params.toml	(date 1647783559260)
@@ -91,5 +91,5 @@
 
 [menu]
   [menu.section]
-    auto = true
+    auto = false
     collapsibleSidebar = true
```

### Expected result

The menu order shouldn't differ between menu types.

### Actual result

There is an obvious difference.

### Environment

```
> @hyas/doks@0.4.0 precheck
> npm version

{
  '@hyas/doks': '0.4.0',
  npm: '8.1.2',
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

> @hyas/doks@0.4.0 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.92.1-85E2E862+extended windows/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio

**Comment by james-d-elliott** [comment]
> Manual versus auto menu generation:
> 
>     * The manual generated menus are build following the definition in the menu config file (`.Menu`)
> 
>     * The auto generated menus are build using the page tree structure (`.Page`)

Ahhh!! This makes lots of sense now as to what I was seeing. 

> However, the auto generated menus do respect the weight defined in the front matter of the pages (tested + confirmed).

https://github.com/h-enk/doks/blob/master/layouts/partials/sidebar/auto-collapsible-menu.html#L6

Changing .Reverse to .ByWeight fixes the issue you described. :)

**Comment by h-enk** [comment]
> Changing .Reverse to .ByWeight fixes the issue you described. :) However this may cause an issue for those not utilizing weight in their front matter?

Good one. I made it `{{ range .Sections.ByWeight.Reverse }}` — see also 7a7c4d75ead5a5924405390ad869fc9133721b31 (tested). If no weight is defined, Hugo's default ordering behavior still applies: Weight > Date > LinkTitle > FilePath (tested).

> I doubt there is a way to fix it so it works in the autogenerated way and respects the manual menu definitions, that seems like a mess

Yeah, absolutely, think so too. I don't wanna go there.

>  I think it's reasonable just to fix the autogenerated menu's honoring the front matter weight. What do you think?

Agree

> I think the only other fix is to clearly document this behavior somehow

Yes, I  will explain this in the documentation.

**Comment by james-d-elliott** [comment]
> Good one. I made it `{{ range .Sections.ByWeight.Reverse }}` — see also [7a7c4d7](https://github.com/h-enk/doks/commit/7a7c4d75ead5a5924405390ad869fc9133721b31) (tested). If no weight is defined, Hugo's default ordering behavior still applies: Weight > Date > LinkTitle > FilePath (tested).

Oh neat, so it first sorts by weight then anything with the same weight is sorted in with `.Reverse`?

**Comment by h-enk** [comment]
> Oh neat, so it first sorts by weight then anything with the same weight is sorted in with .Reverse?

Yes, that's correct

**Comment by h-enk** [comment]
I've updated [Section navigation](https://getdoks.org/docs/recipes/menus/#section-navigation) on the Menus page

**Comment by james-d-elliott** [comment]
Nice! It's obvious once you explained the difference, just wasn't without. That section explains it really well now.

**Comment by kevinrue** [comment]
> > Oh neat, so it first sorts by weight then anything with the same weight is sorted in with .Reverse?

> Yes, that's correct

From my experience, it's actually sorting by reverse weight (not breaking ties as described here) which is not the desired behaviour. (see #781). I would like to remove the `.Reverse` to order navigation links in increasing weight, like every other menu I've come across so far.
