### ISSUE TITLE
Details layout is not correct under Firefox

### ISSUE THREAD

**Issue by Vorlif** [h-enk/doks#720]
## Description

First of all, thanks for the great theme. I wanted to try the new details today and realized that they don't look as "nice" on me as they do on your screenshots.

The layout of the details looks "not nice" under Firefox. I would even say buggy.

### Steps to reproduce

Open the [details examples](https://getdoks.org/docs/recipes/details/) with Firefox

### Expected result

The details should look the same with Firefox as with Chrome. Or something like that... :blush: 

### Actual result

![grafik](https://user-images.githubusercontent.com/4333770/161206816-b8a4e3cc-da9e-4939-a1b4-83c3de29dc4b.png)
![grafik](https://user-images.githubusercontent.com/4333770/161206852-69307554-5282-4778-9b24-56f89a1775f4.png)
![grafik](https://user-images.githubusercontent.com/4333770/161206997-abfdba80-fc97-47a7-a703-764f7701cc75.png)

### Environment

* Arch linux
* Firefox 98.0.2 (64-Bit)

**Comment by h-enk** [comment]
Thanks for reporting. Confirmed and looking into it.

**Comment by h-enk** [comment]
Fixed w/ d4b6900c965da251d02834bf4a7eb17e6f12e3d2. Will be part of a security patch (Doks v0.4.2) later today.

**Comment by h-enk** [comment]
Released: Doks [v0.4.2](https://github.com/h-enk/doks/releases/tag/v0.4.2)
