### ISSUE TITLE
wrong links in main menu

### ISSUE THREAD

**Issue by Flashpok** [h-enk/doks#726]
## Description

Thank you for this wonderful theme. 

After pushing Hugo to Gitlab (here: https://gitlab.com/hugo1111/dok1), all pages are redirected to "Page not found :(" pages, because the URL is wrong : 

baseURL : https://hugo1111.gitlab.io/dok1/

But the links in the main menus are broken because they replace dok1 by "dok1/dok1".

For example :  https://hugo1111.gitlab.io/dok1/dok1/blog/

What is wrong ? A bug ? My configuration ?

Thank you for your help !!

### Environment

` '@hyas/doks': '0.4.2',
  npm: '8.5.0',
  node: '16.14.2',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1n+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

> @hyas/doks@0.4.2 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended linux/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=gohugoio
`

**Comment by h-enk** [comment]
> Thank you for this wonderful theme.

Thanks!

Please see https://github.com/h-enk/doks/discussions/98#discussioncomment-326932

**Comment by h-enk** [comment]
Aside) Maybe also of interest for you: https://github.com/h-enk/doks/discussions/184
