### ISSUE TITLE
Including SVGs in Markdown results in 

### ISSUE THREAD

**Issue by johnnymatthews** [h-enk/doks#736]
I have the following page bundle:

```plaintext
content
├── en
└──── basics/
        ├── index.md
        ├── picture.svg
        └── picture.png
```

Inside `index.md` I have the following:

```markdown
# Page title

Lorem ipsum here is a picture:

![Picture text.](picture.png).
```

This works perfectly fine, and the site builds normally. However, if I want to use the `.svg` version of this image, then I get the following error:

```shell
ERROR 2022/04/28 12:33:18 "/home/io/Code/lotus-docs/layouts/_default/_markup/render-image.html:2:18": execute of template failed: template: _default/_markup/render-image.html:2:18: executing "_default/_markup/render-image.html" at <$image.Resize>: error calling Resize: *resources.genericResource is not an image
```

If I switch the image reference back to the `.png` version, then the site builds normally again.

Is there a special way to reference SVGs in Doks?

**Comment by ynwd** [comment]
same here

**Comment by h-enk** [comment]
> Is there a special way to reference SVGs in Doks?

No, SVG (and WebP) are not supported yet. Will certainly be added!
