### ISSUE TITLE
Adding many pages results in "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by steven-mathew** [h-enk/doks#738]
## Description

I was building an auto-documentation script for a large codebase and noticed that when adding 2000+ pages, the search bar stops working.

#### Clone the repo and implement `auto.py` which creates 2000 pages

```bash
git clone https://github.com/h-enk/doks.git my-doks-site && cd my-doks-site
npm install
touch content/en/docs/prologue/auto.py
```

```python
# In content/en/docs/prologue/auto.py

for i in range(1, 2000):
    title = "---\n"
    title += f'title: "doc{i}"'
    title += "\n"
    rest = r"""description: "Doks comes with commands for common tasks."
lead: "Doks comes with commands for common tasks."
date: 2020-10-13T15:21:01+02:00
lastmod: 2020-10-13T15:21:01+02:00
draft: false
images: []
menu:
  docs:
    parent: "prologue"
weight: 130
toc: true
---
"""
    header = title + rest
    with open(f"content/en/docs/prologue/doc{i}.md", "w", encoding="utf-8") as f:
        f.write(header)
```

#### Generate the pages and start up the server

```bash
python3 content/en/docs/prologue/auto.py
# We use --renderToDisk because, by default, hugo serves files from memory.
exec-bin node_modules/.bin/hugo/hugo server --bind=0.0.0.0 --disableFastRender --renderToDisk
```
Visit [http://localhost:1313/docs/prologue/introduction](http://localhost:1313/docs/prologue/introduction) and navigate to the search bar on any browser but Safari. Here are the following browsers wherein the search bar worked:
- [ ] Chrome 101.0.4951.41 (Official Build) (arm64)
- [ ] Firefox Developer 100.0b3 (64-bit)
- [x] Safari 14.1.2 (16611.3.10.1.6) 

### Expected result

The search bar should work.

### Actual result

The search bar doesn't work and we get [Error: Out of stack space (Edge) or InternalError: too much recursion (Firefox) or RangeError: Maximum call stack size exceeded (Chrome)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Too_much_recursion).

### Environment

```
> @hyas/doks@0.4.2 precheck
> npm version

{
  '@hyas/doks': '0.4.2',
  npm: '8.6.0',
  node: '18.0.0',
  v8: '10.1.124.8-node.13',
  uv: '1.44.1',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1n',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}

> @hyas/doks@0.4.2 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended darwin/arm64 BuildDate=2022-03-26T09:15:58Z VendorInfo=gohugoio
```

**Comment by h-enk** [comment]
Confirmed
