### ISSUE TITLE
Failed create new page

### ISSUE THREAD

**Issue by acoilier** [h-enk/doks#74]
## Description

Error while creating a new page with the hugo command.

### Steps to reproduce

`hugo new ...`

### Expected result
Create new page

### Actual result
`Error: "/data/doks/layouts/partials/head/seo.html:33:1": parse failed: template: partials/head/seo.html:33: unexpected "-" in else`

### Environment

just after a `git clone`

**Comment by acoilier** [comment]
There was also an error when activating the privacy page in the footer. 404 error.

Thanks for everything, I'm a fan of the project ;)

**Comment by h-enk** [comment]
Hi, @acoilier, thanks for using Doks.

I couldn't reproduce your error. However, I noticed an extra space in the else statement of your error message. I removed that now — could you please check again?

If that didn't help, could you give me (temporarily) access to your repo, so I could check further?

**Comment by acoilier** [comment]
Thank you very much that was the problem.
I'm on Debian now, so I'll switch to Ubuntu to get a newer version of Node.js.
