### ISSUE TITLE
Image quality loss in navbar

### ISSUE THREAD

**Issue by constantcopyandwork** [h-enk/doks#749]
## Description

Low quality images in navbar. 

### Steps to reproduce

Any image added to the navigation bar ends up blurry. Social icons in demo site already show this quality loss. If I add a png there it is even more evident. Am I missing something?

### Expected result

Images should have minimum resolution setting. 

### Actual result

Images (tested png and svg) added to navbar end up with low quality.

**Comment by h-enk** [comment]
I would recommend using SVG (and not PNG) in the navigation bar — see also: [SVG: Scalable Vector Graphics](https://developer.mozilla.org/en-US/docs/Web/SVG?retiredLocale=nl)

> Images (tested png and svg) added to navbar end up with low quality.

Cannot confirm that (and it surprises me for SVG images) — maybe something to do w/ your browser settings (did you try other browsers?):

![Snag_10090f8](https://user-images.githubusercontent.com/3902872/168806416-8c6698b1-aee7-4ed1-acc0-3e4e382f8afc.png)

This is how they are added: https://github.com/h-enk/doks/blob/master/config/_default/menus/menus.en.toml#L69

If the issue persists for you, could you please share a repo?

**Comment by constantcopyandwork** [comment]
So, apparently that's a thing: https://graphicdesign.stackexchange.com/questions/32100/quality-loss-when-scaling-down-svgs

I circumvented it on my logo by using the svg version. And I'll just ignore it for now. With the svg it's barely there, really.

Probably related to my NOT high def screens.

P.S.: I'll work on a repo soon and can share later. But I don't know if it's pertinent. The (tiny) issue is more on the icon designers' side, I think.
