### ISSUE TITLE
npm run start just gives me file not found

### ISSUE THREAD

**Issue by BlockchainZero** [h-enk/doks#77]
## Description
 npm run start doesnt work it says file not found

### Steps to reproduce

After running npm install, everything goes well,
then I do npm run start and go to the localhost and it says file not found.

**this is what shows up when I do npm run start**

Quotz@The-Tardis my-doks-site % npm run start

> doks@0.1.5 prestart /Users/Quotz/Desktop/doks/themes/my-doks-site
> npm run clean

> doks@0.1.5 clean /Users/Quotz/Desktop/doks/themes/my-doks-site
> rimraf public resources functions

> doks@0.1.5 start /Users/Quotz/Desktop/doks/themes/my-doks-site
> hugo server --disableFastRender

Start building sites … 

                   | EN  
-------------------+-----
  Pages            | 29  
  Paginator pages  |  0  
  Non-page files   |  1  
  Static files     | 25  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 349 ms
Watching for changes in /Users/Quotz/Desktop/doks/themes/my-doks-site/{archetypes,assets,babel.config.js,content,data,layouts,node_modules,package.json,static}
Watching for config changes in /Users/Quotz/Desktop/doks/themes/my-doks-site/config/_default
Environment: "development"
Serving pages from memory
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)

**And here it is when I do npm install**

Quotz@The-Tardis my-doks-site % npm install
npm WARN bootstrap@4.5.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.3 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.

audited 1232 packages in 5.828s

86 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by h-enk** [comment]
Hello @BlockchainZero, I cannot reproduce your error. Your `npm install` output and `npm run start` output both look good.

I don't see what you mean with "it (nmp run start) says file not found"?

Are you able to access `localhost:1313`, does it give you more details on file not found (if that's the case)?

**Comment by BlockchainZero** [comment]
Okay now I see what the problem was, when I put localhost:1313 in the url it works, but when I put //localhost:1313/ it doesnt work both on Firefox and Chrome, it simply says file not found. I put the latter on the URL because in terminal when I run ">npm run start" the output shows " Web Server is available at //localhost:1313/ (bind address xxxxxxx)" so I just copy pasted it.

But yeah it works fine when I put localhost:1313!
