### ISSUE TITLE
Blog archetype has DOS line endings

### ISSUE THREAD

**Issue by NatTuck** [h-enk/doks#779]
## Description

hugo new content/blog/... produces a file with DOS line endings.

This is only an issue for blog posts. The docs archetype is fine.

### Steps to reproduce
 
 - Working in an OS other than Windows
 - Make new site (Child theme)
 - hugo new content/blog/foo/index.md
 - cat -veT content/blog/foo/index.md

```
---^M$
title: "{{ replace .Name "-" " " | title }}"^M$
description: ""^M$
...
```

### Expected result

No ^M at the end of each line because the file has native line endings.

### Actual result

The other thing.

### Environment

> doks-child-theme@0.4.3 precheck
> npm version

{
  'doks-child-theme': '0.4.3',
  npm: '7.24.1',
  node: '14.17.5',
  v8: '8.4.371.23-node.76',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}

> doks-child-theme@0.4.3 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.99.0-1de333e7a3fc863672ec6d6cd53ba66dbcdd2305+extended linux/amd64 BuildDate=2022-05-16T08:10:56Z VendorInfo=gohugoio

$ hugo --version

hugo v0.100.1-0afb4866e345d31cbbcbab4349e43f1d36122806+extended linux/amd64 BuildDate=2022-06-01T10:11:48Z VendorInfo=gohugoio

**Comment by h-enk** [comment]
Thanks for reporting this. I'm not quite sure how to fix this (and I can't use my Manjaro machine right now).

On Windows, in Visual Studio code, I see that both `./archetypes/docs.md` and `./archetypes/blog.md` (and all other Doks files) use CRLF — so, not LF. Note that, `end_of_line = lf` in `.editorconfig` — see also [EditorConfig](https://editorconfig.org/)

Could you try with copying `./node_modules/@hyas/doks/archetypes/*` to `./archetypes/*` (so that the virtual mount is not used)? Or, do you have any other ideas? Thanks!

**Comment by NatTuck** [comment]
I copied the blog archetype out of ```node_modules``` and removed the bad line endings, which fixed it for me for the moment.

Testing again, apparently I was just wrong about the docs archetype being correct. Running ```npm run create content/docs/foo.md``` gives me CRs in the resulting file as well.

When I directly clone this repo, I get correct line endings. If I manually ```npm install @hyas/doks``` in an empty directory I get DOS line endings under ```node_modules```. That's true for all the .md files in the repo that I checked.

This might be related? https://github.com/npm/npm/issues/2097

**Comment by james-d-elliott** [comment]
Can you try with that PR? I suspect it should fix it.

**Comment by james-d-elliott** [comment]
Actually looking again with `git ls-files --eol`:

```
i/lf    w/lf    attr/                   archetypes/default.md
i/lf    w/lf    attr/                   archetypes/docs.md
i/lf    w/lf    attr/                   archetypes/docs/_index.md
i/lf    w/lf    attr/                   archetypes/docs/lorem/_index.md
i/lf    w/lf    attr/                   archetypes/docs/lorem/ipsum/index.md
```

This seems to probably be some form of local issue maybe? The index has these files all ending with LF.

**Comment by NatTuck** [comment]
I think it's fine in git. My suspicion is that it's a problem with running "npm publish" from Windows, hence only seeing the issue with npm packages and not git checkouts.

**Comment by james-d-elliott** [comment]
Yeah that's probably more likely the cause. Beyond my knowledge though.

**Comment by NatTuck** [comment]
Looks like the npm people recommend fixing it in a prepublish hook: https://github.com/npm/npm/issues/12371

**Comment by h-enk** [comment]
> Looks like the npm people recommend fixing it in a prepublish hook: https://github.com/npm/npm/issues/12371

Hmm..

Would it be something to try shipping the next version of the Doks themes (both parent and child) using LF (on all files)? See if that helps, or wouldn't that make sense?

I was thinking of converting the line endings with something like `sed -i 's/\r$//' **/*.md` (et cetera). Or, Nat, do you have ideas for a smarter way to bulk convert? Thanks!
