### ISSUE TITLE
Inverted ordering of navigation menu

### ISSUE THREAD

**Issue by kevinrue** [h-enk/doks#781]
## Description

Weights order navigation link in reverse order. I had to use negative weights in the `_index.md` files of each section to restore the correct order.
For instance: https://github.com/kevinrue/wimm_ccb_doks/blob/master/content/en/docs/ssh/_index.md

Also, the weight of the `[[docs]]` entries in `config/_default/menus/menus.en.toml` do not seem to have any impact on the ordering unless I set `auto = false` in `config/_default/params.toml`. 

```
[menu]
  [menu.section]
    auto = true
```

### Steps to reproduce

Public repository here: https://github.com/kevinrue/wimm_ccb_doks

### Expected result

This is the desired ordering 

![image](https://user-images.githubusercontent.com/5769108/172837115-6507b043-fd03-442c-96a8-ce6454044d77.png)

### Actual result

Collapsible menu items (prologue, vpn, ssh, bash, help) were ordered in reverse order.

### Environment

Paste the information here as shown by `npm run check`

```
> @hyas/doks@0.4.3 precheck
> npm version

{
  '@hyas/doks': '0.4.3',
  npm: '7.14.0',
  node: '14.15.4',
  v8: '8.4.371.19-node.17',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}

> @hyas/doks@0.4.3 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.99.0-1de333e7a3fc863672ec6d6cd53ba66dbcdd2305+extended darwin/amd64 BuildDate=2022-05-16T08:10:56Z VendorInfo=gohugoio
```

**Comment by h-enk** [comment]
See https://github.com/h-enk/doks/issues/709 + https://github.com/h-enk/doks/discussions/774

**Comment by kevinrue** [comment]
Thank you for the links to closed issues. I have read them and now I am confused as to why `.Reverse`  is present in 
https://github.com/h-enk/doks/blob/master/layouts/partials/sidebar/auto-collapsible-menu.html#L6

I have just removed `.Reverse` , i.e.
```
    {{ range .Sections.ByWeight }}
```
and this fixes the ordering for me, respecting the weights set in the front matter of the various sections in increasing order (like any other menu).

Why would one want to reverse the order in this case?

(Sorry if it's a silly question, I've been using this type of static templates a few times now, without going into the details of their implementation.)

**Comment by roheclassic** [comment]
> Why would one want to reverse the order in this case?

I'm also one of those who feels strange that.😕

**Comment by james-d-elliott** [comment]
Also see #774

**Comment by h-enk** [comment]
To be quite honest, I've noticed this behavior too, when working on the new menu structure for getdoks.org. What I did, I updated the Doks default `{{ range .Sections.ByWeight.Reverse }}` to `{{ range .Sections }}`. 

With the  Hugo default sort order in mind (Weight > Date > LinkTitle > FilePath — see also the Hugo docs: [Order Content](https://gohugo.io/templates/lists/#order-content)), I now think (`{{ range .Sections }}`) should become the new Doks default.

Or, am I missing something?

**Comment by kevinrue** [comment]
I don't have an opinion (yet) about multiple sort levels, as I currently only use the weight. I think I've also made my own preference clear [earlier](https://github.com/h-enk/doks/issues/781#issuecomment-1151340376), i.e. collapsible sections being ordered in increasing weight.

That was really my only query/request in this thread. Everything else, I'm happy to leave the discussion to you guys.

**Comment by kevinrue** [comment]
Here's me applying the fix to my own repo (linked in the first post of this thread)
https://github.com/OBDS-Training/Help/commit/bc0484003d767330339b209f3547bcf6527f3b4d

thanks for the feedback!
