### ISSUE TITLE
CSS class .offcanvas-backdrop is missing after static build.

### ISSUE THREAD

**Issue by hschneider** [h-enk/doks#848]
## Description

Clicking an offcanvas menu does not show the dark backdrop under the menu.

### Steps to reproduce

npm run build
Upload /public to some webserver or use a local server.

### Expected result

The semi-transparent black overlay should be shown.

### Actual result

No overlay visible at all.
Class .offcanvas-backdrop seems to be missing in the page's source.

### Environment

> doks-child-theme@0.5.0 precheck
> npm version

{
  'doks-child-theme': '0.5.0',
  npm: '8.11.0',
  node: '16.16.0',
  v8: '9.4.146.24-node.21',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '1.1.1q+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

> doks-child-theme@0.5.0 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended darwin/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

**Comment by oscome** [comment]
@hschneider  Good job.I had the same bug.Thanks!
