### ISSUE TITLE
Blog pagination selector is left-aligned

### ISSUE THREAD

**Issue by pavithraes** [h-enk/doks#853]
## Description

I'm using the new updates to the blog pages (thank you so much for this!), and noticed the page selector is left aligned.

![Screenshot 2022-07-23 at 9 38 33 PM](https://user-images.githubusercontent.com/33131404/180613251-f19deb89-affb-4b04-910e-4672f0fbb3bb.png)

### Steps to reproduce

We need to just get the pagination, so the easiest way might be to add another blog page and set `paginate = 2` in `config/_default/config.toml`. (I haven't deployed my updates yet, so I can't share a live page right now, but I'll add it here whenever I do!))

### Expected result

It should be center aligned.

I was able to fix this by wrapping lines 28 and 29 here:

https://github.com/h-enk/doks/blob/60768e606844d16d50c7b8c111a866792ee26435/layouts/_default/list.html#L26-L31

in a `<div class="justify-content-center" style="display:flex">`

I'm by no means an expect in html/css, so there's probably a nicer way to do this. :)

**Comment by h-enk** [comment]
Thanks, I will be looking into this fiurther

**Comment by jbspeakr** [comment]
quick fix for the meantime – add this to your `_pages.scss`:

```
ul.pagination {
  justify-content: center !important;
}
```
