### ISSUE TITLE
If enable toTopButton = true, The link covered by the button cannot be clicked

### ISSUE THREAD

**Issue by dualbios4** [h-enk/doks#863]
If enable toTopButton = true, and scroll the site the link covered/on a line by the button cannot be clicked

**Comment by tuyenld** [comment]
I have the same issue.

**Comment by h-enk** [comment]
Will be loooking into it

**Comment by h-enk** [comment]
Confirmed — look like a `z-index` issue. Will be fixed.

![Snag_1d8b824d](https://user-images.githubusercontent.com/3902872/188381422-b5f28d3d-cbfe-4fb3-ba07-265e4904cf5c.png)
