### ISSUE TITLE
hugo generates a file error, how to escape */?

### ISSUE THREAD

**Issue by sundayfly** [h-enk/doks#875]
Error: Error building site: MINIFY: failed to transform "index.js" (application/javascript): unexpected '\n\u0026gt;\u0026gt;\u0026gt; text2 = ' in expression on line 137 and column 672
  137: ...this is a comment */'\n\u0026gt;\u0026gt;...

Post Content

already wrapped with \```py \``` symbols
```py
>>> comment = re.compile(r'/\*(.*?)\*/')
>>> text1 = '/* this is a comment */'
>>> text2 = '''/* this is a
... multiline comment */
... '''
```

Escape can be compiled, but it will affect the original meaning
```
>>> comment = re.compile(r'/\*(.*?)\*\/')
>>> text1 = '/* this is a comment *\/'
>>> text2 = '''/* this is a
... multiline comment *\/
... '''
```

**Comment by james-d-elliott** [comment]
Related possibly to #716

**Comment by h-enk** [comment]
Could you please check if this fixes it for you: https://github.com/h-enk/hyas-themes-doks/issues/1

**Comment by sundayfly** [comment]
thanks, it's resolved 

> h-enk/hyas-themes-doks#1



> Related possibly to #716
