### ISSUE TITLE
Search bar hidden in side-nav on mobile

### ISSUE THREAD

**Issue by percula** [h-enk/doks#876]
## Description

Previously (at least in 0.4.2), the search bar would appear underneath the top navigation bar on mobile devices. This was super useful. However, in the latest master, this doesn't happen. Perhaps this was done intentionally. If so, it would be great if there was a configuration flag to re-enable the previous behavior.

### Steps to reproduce

Download the latest master build and start the server. Use dev tools to make the window the size of a phone.

### Expected result

The search bar should be visible underneath the top navigation bar.

### Actual result

The search bar is hidden in the side menu.

### Environment

```

> @hyas/doks@0.5.0 precheck
> npm version

{
  '@hyas/doks': '0.5.0',
  npm: '8.5.0',
  node: '16.14.2',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1n+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

> @hyas/doks@0.5.0 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended darwin/arm64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
```

**Comment by percula** [comment]
Here's some screenshots showing the before/after:

### v0.4.2:

![localhost_56417_docs_prologue_introduction_(iPhone 12 Pro)](https://user-images.githubusercontent.com/16809252/186493482-e74aff2b-c6e8-479d-bdb1-50502e15018e.png) 

### v0.5.0:
![localhost_53744_docs_prologue_introduction_(iPhone 12 Pro)](https://user-images.githubusercontent.com/16809252/186493488-34b56c3e-03b9-452a-a498-f5aff3ea25b5.png)

**Comment by h-enk** [comment]
Get that /I will be considering this. I'm also thinking of putting Search in the top bar. I will get back to you on this.

**Comment by percula** [comment]
@h-enk Thanks! Yeah, what would be ideal would be a search icon in the top bar that expands when tapped. I am not skilled enough to do that with Hugo (I could do it in Flutter or Android), but hopefully you are 🙂.
