### ISSUE TITLE
Breadcrumbs don’t match permalinks

### ISSUE THREAD

**Issue by genebean** [h-enk/doks#885]
## Description

I’ve renamed “docs” to “info” via the permalink settings, but the breadcrumbs still say docs. 

### Steps to reproduce

Change docs permalink to have any word other than docs at the beginning 

### Expected result

Breadcrumbs match url/permalink 

### Actual result

Still says docs.

**Comment by h-enk** [comment]
> I’ve renamed “docs” to “info” via the permalink settings, but the breadcrumbs still say docs.

Next to that: 
1. rename `./content/en/docs/` to `./content/en/info/`, and
2.  copy `./layouts/docs/`, and paste as `./layouts/info/`

Ad 1) this will create the node `info` (as used by the breadcrumb)
Ad 2) this will make sure the content in `info` will be displayed like the content in `docs`

Linked discussion: https://github.com/h-enk/doks/discussions/882

**Comment by genebean** [comment]
> 2. copy `./layouts/docs/`, and paste as `./layouts/info/`
> 

I am using a child theme so I don’t have that path in my code tree. I’m attempting to not do things that will get out of sync with your theme as it updates… is there any way to do this via configuration in one of the toml files or in the frontmatter?

**Comment by h-enk** [comment]
You would then have to copy `./node_modules/@hyas/doks/layouts/docs/list.html` + `./node_modules/@hyas/doks/layouts/docs/single.html` and paste as `./layouts/info/list.html` + `/layouts/info/single.html` respectively.

Or, add `type: "docs"` in the frontmatter of your content in the `info` directory — see also the Hugo docs: [Front Matter Variables](https://gohugo.io/content-management/front-matter/#front-matter-variables). Not tested though, it could be that you need to be more specific ( it works for `type: "about"` with an `about.html` template).

**Comment by genebean** [comment]
Closing as the actual issue at hand has been solved.
