### ISSUE TITLE
Multiple things broken on iOS

### ISSUE THREAD

**Issue by pensivedog** [h-enk/doks#920]
Several Doks features aren't working on my iPhone 6. I've tested in both Safari and Chrome with the same result:

1. images don't appear at all in the blog list layout
2. images appear but remain blurred up in the blog single layout
3. hamburger menu doesn't open or respond to touch
4. light/dark mode can't be toggled
5. alerts cannot be dismissed

**Comment by h-enk** [comment]
Do you have a repo / site you can share?

**Comment by pensivedog** [comment]
Not at the moment. But issues 1-4 are happening on getdoks.org and doks.netlify.app, so I assume 5 would also also be an issue there if an alert were enabled.

I only have an iPhone 6 running iOS 12.5, so I'm unable to test if it's also an issue on newer versions.

**Comment by h-enk** [comment]
Looks like your phone's Content Security Policy settings is causing issues. I will run some tests tomorrow + get back to you

**Comment by h-enk** [comment]
Ran some tests on BrowserStack /confirmed. Getting issues with iPhone 6 + 7 (iOS 11/12):

![Snag_1921889e](https://user-images.githubusercontent.com/3902872/193999999-c11b92f2-2163-4196-ba15-0cf77b66ae58.png)

Console errors for scripts Bootstrap, highlight, main, and FlexSearch:

![Snag_1922b8a2](https://user-images.githubusercontent.com/3902872/194000191-219c8dd3-172d-4c53-bddb-151c7d5c3e19.png)

Working correctly /as expected for iPhone 8 (iOS 14) and up.

![Snag_1921ebad](https://user-images.githubusercontent.com/3902872/194000055-510654a9-a67f-48e3-941a-eb236aa541fb.png)

Conclusion: can't /won't fix Bootstrap, highlight, and FlexSearch. So, it looks like you need a new phone ...
