### ISSUE TITLE
Adding scrollbars to overflowing tables

### ISSUE THREAD

**Issue by andreaslennartz** [h-enk/doks#990]
## Summary

Just a small css / scss addition.

Consider using a table in markdown, e.g. something like 
```
Id|Description|CustomerName|Quantity
--|-----------|------------|--------
10100|T-Shirts: 7|Clark Kent|7
10200|Jeans: 12|Peter Parker|12
```

Depending on the device, the table may exceed the viewport (e.g. with width of the table may be large than the available size.
By default, the table columns are not wrapped. 
Would be good to have scrollbars here when the table overflows. 

### Basic example
To archive the scrollbars, I adjusted the scss: 

```
table {
  display: block;
  overflow-x: auto;
  white-space: nowrap;
  
  tbody {
    display: table;
    width: 100%;
 }
}
```

**Comment by h-enk** [comment]
Good one! I think we'll have to make this as easy as possible, using e.g. your SCSS snippet. Unfortunately, there's no [Markdown Render Hook](https://gohugo.io/templates/render-hooks/) for tables  — yet.

See also: [Responsive tables ](https://getbootstrap.com/docs/5.3/content/tables/#responsive-tables), making this work:

```md
<div class="table-responsive">

Id|Description|CustomerName|Quantity
--|-----------|------------|--------
10100|T-Shirts: 7|Clark Kent|7
10200|Jeans: 12|Peter Parker|12
{.table}
</div>
```

**Comment by andreaslennartz** [comment]
I wasn't aware of the render hooks, which are actually quite interesting - thanks for pointing it out!
The code snippet works for me so far, but I don't have enough knowledge on css/html5/bootstrap to see the difference between two approaches. But likely the bootstrap variant is more consistent with the overall design.
